//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFATERPWebApplication.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class AddOn
    {
        public int RecordKey { get; set; }
        public string ApplCode { get; set; }
        public string ApplFor { get; set; }
        public string AuthIds { get; set; }
        public string Authorise { get; set; }
        public bool AutoCode { get; set; }
        public bool AutoDescr { get; set; }
        public string BackColor { get; set; }
        public decimal Decimals { get; set; }
        public string Dft { get; set; }
        public int DftSno { get; set; }
        public bool DontUpdate { get; set; }
        public System.DateTime EffDate { get; set; }
        public System.DateTime EffDate2 { get; set; }
        public string Eqsn { get; set; }
        public string Fld { get; set; }
        public int FldSize { get; set; }
        public string FldType { get; set; }
        public bool ForceUpdate { get; set; }
        public bool GridValues { get; set; }
        public string Head { get; set; }
        public string Hide { get; set; }
        public string HWSerial { get; set; }
        public string HWSerial2 { get; set; }
        public bool InActive { get; set; }
        public string Lock { get; set; }
        public string MainType { get; set; }
        public bool ManualChange { get; set; }
        public int MinPrefix { get; set; }
        public int MinSize { get; set; }
        public bool NoCaption { get; set; }
        public bool PlaceInLine { get; set; }
        public string PlaceValue { get; set; }
        public string Prefix { get; set; }
        public string QueryText { get; set; }
        public string Reqd { get; set; }
        public int RoundedTo { get; set; }
        public bool SendEmail { get; set; }
        public bool SendSMS { get; set; }
        public int Sno { get; set; }
        public string SubType { get; set; }
        public string Type { get; set; }
        public string Users { get; set; }
        public int Width { get; set; }
        public decimal TOUCHVALUE { get; set; }
        public string EnteredBy { get; set; }
        public System.DateTime LastUpdateDate { get; set; }
    }
}
