//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFATERPWebApplication.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class AddonsIG
    {
        public int RecordKey { get; set; }
        public string Authorise { get; set; }
        public string Dft { get; set; }
        public int DftSno { get; set; }
        public string Eqsn { get; set; }
        public string Fld { get; set; }
        public int FldSize { get; set; }
        public string FldType { get; set; }
        public bool GridValues { get; set; }
        public string Head { get; set; }
        public string Hide { get; set; }
        public string HWSerial { get; set; }
        public string HWSerial2 { get; set; }
        public string Lock { get; set; }
        public string OptionCode { get; set; }
        public string QueryText { get; set; }
        public string Reqd { get; set; }
        public decimal TOUCHVALUE { get; set; }
        public string EnteredBy { get; set; }
        public System.DateTime LastUpdateDate { get; set; }
        public string AUTHIDS { get; set; }
    }
}
