//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFATERPWebApplication.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class AddOn_D
    {
        public int RecordKey { get; set; }
        public string AuthIds { get; set; }
        public string Authorise { get; set; }
        public string CheckedAddOns { get; set; }
        public string Code { get; set; }
        public string HWSerial { get; set; }
        public string HWSerial2 { get; set; }
        public string Branch { get; set; }
        public string Type { get; set; }
        public string Prefix { get; set; }
        public string Srl { get; set; }
        public System.DateTime DocDate { get; set; }
        public string F001 { get; set; }
        public decimal TouchValue { get; set; }
        public string Sno { get; set; }
        public string EnteredBy { get; set; }
        public System.DateTime LastUpdateDate { get; set; }
    }
}
