//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFATERPWebApplication.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public int RecordKey { get; set; }
        public short AddOrContact { get; set; }
        public string Adrl1 { get; set; }
        public string Adrl2 { get; set; }
        public string Adrl3 { get; set; }
        public string Adrl4 { get; set; }
        public System.DateTime Anndate { get; set; }
        public string Area { get; set; }
        public string AssistEmail { get; set; }
        public string AssistMobile { get; set; }
        public string AssistName { get; set; }
        public string AssistTel { get; set; }
        public string AuthIds { get; set; }
        public string Authorise { get; set; }
        public string BaseGr { get; set; }
        public System.DateTime Bdate { get; set; }
        public System.DateTime ChildBdate { get; set; }
        public string ChildName { get; set; }
        public string City { get; set; }
        public string Code { get; set; }
        public string ContEmail { get; set; }
        public string ContMobile { get; set; }
        public string ContTelephone { get; set; }
        public string CorpID { get; set; }
        public string CorrespondenceType { get; set; }
        public string Country { get; set; }
        public string CSTNo { get; set; }
        public string Dept { get; set; }
        public int Designation { get; set; }
        public string Division { get; set; }
        public string DraweeBank { get; set; }
        public string EMail { get; set; }
        public string Fax { get; set; }
        public string HWSerial { get; set; }
        public string HWSerial2 { get; set; }
        public string Language { get; set; }
        public System.DateTime LastDate { get; set; }
        public string LastFormat { get; set; }
        public decimal LastOS { get; set; }
        public string LastRemark { get; set; }
        public string LBTNo { get; set; }
        public string LeadCode { get; set; }
        public string LFlag { get; set; }
        public string Licence1 { get; set; }
        public string Licence2 { get; set; }
        public string LstNo { get; set; }
        public string MailingCategory { get; set; }
        public string Mobile { get; set; }
        public string Name { get; set; }
        public string PanNo { get; set; }
        public string Password { get; set; }
        public string Person { get; set; }
        public string PhotoPath { get; set; }
        public string Pin { get; set; }
        public string PTaxCode { get; set; }
        public string PTaxOST { get; set; }
        public string Religion { get; set; }
        public string Segment { get; set; }
        public string ServiceTaxNo { get; set; }
        public int Sno { get; set; }
        public int Source { get; set; }
        public System.DateTime SpouseBdate { get; set; }
        public string SpouseName { get; set; }
        public int State { get; set; }
        public string STaxCode { get; set; }
        public string STaxOST { get; set; }
        public string Tel1 { get; set; }
        public string Tel2 { get; set; }
        public string Tel3 { get; set; }
        public string Tel4 { get; set; }
        public string TINNo { get; set; }
        public decimal TouchValue { get; set; }
        public string UserID { get; set; }
        public string VATReg { get; set; }
        public string www { get; set; }
        public string EnteredBy { get; set; }
        public System.DateTime LastUpdateDate { get; set; }
    
        public virtual ContactSource ContactSource { get; set; }
        public virtual TfatState TfatState { get; set; }
        public virtual TaxMaster TaxMaster { get; set; }
        public virtual TaxMaster TaxMaster1 { get; set; }
    }
}
