//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFATERPWebApplication.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attachment
    {
        public int RecordKey { get; set; }
        public string AccPeriod { get; set; }
        public string AuthIds { get; set; }
        public string Authorise { get; set; }
        public string Branch { get; set; }
        public string Code { get; set; }
        public string FilePath { get; set; }
        public string HWSerial { get; set; }
        public string PeriodCode { get; set; }
        public string Prefix { get; set; }
        public string Sno { get; set; }
        public string Srl { get; set; }
        public int SrNo { get; set; }
        public string TableKey { get; set; }
        public string Type { get; set; }
        public decimal TOUCHVALUE { get; set; }
        public string EnteredBy { get; set; }
        public System.DateTime LastUpdateDate { get; set; }
        public string HWSERIAL2 { get; set; }
    
        public virtual Sale Sale { get; set; }
    }
}
