//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFATERPWebApplication.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditTrail
    {
        public int RecordKey { get; set; }
        public string AccPeriod { get; set; }
        public decimal Amt { get; set; }
        public string AuthIds { get; set; }
        public string Authorise { get; set; }
        public string Branch { get; set; }
        public string CompCode { get; set; }
        public System.DateTime Docdate { get; set; }
        public System.DateTime EntryDate { get; set; }
        public string ExeInfo { get; set; }
        public string HWSerial { get; set; }
        public string HWSerial2 { get; set; }
        public string Ids { get; set; }
        public string Narr { get; set; }
        public string Opmode { get; set; }
        public string OptionName { get; set; }
        public string Party { get; set; }
        public string PeriodCode { get; set; }
        public string Prefix { get; set; }
        public string Srl { get; set; }
        public string Type { get; set; }
        public string WorkStation { get; set; }
        public decimal TOUCHVALUE { get; set; }
        public string EnteredBy { get; set; }
        public System.DateTime LastUpdateDate { get; set; }
    }
}
