//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFATERPWebApplication.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Charge
    {
        public int RecordKey { get; set; }
        public bool AfterExcise { get; set; }
        public bool AfterTax { get; set; }
        public string AuthIds { get; set; }
        public string Authorise { get; set; }
        public string Branch { get; set; }
        public string Code { get; set; }
        public string DocType { get; set; }
        public bool DontUse { get; set; }
        public string EqAmt { get; set; }
        public string EqBro { get; set; }
        public string EqCost { get; set; }
        public string EqExc { get; set; }
        public string EqSale { get; set; }
        public string EqSTax { get; set; }
        public string EqTax { get; set; }
        public string Equation { get; set; }
        public string Fld { get; set; }
        public string Head { get; set; }
        public string HWSerial { get; set; }
        public string HWSerial2 { get; set; }
        public string MainType { get; set; }
        public bool Post { get; set; }
        public decimal PostNo { get; set; }
        public decimal RoundOff { get; set; }
        public string SubType { get; set; }
        public string TaxCode { get; set; }
        public bool ToPrint { get; set; }
        public decimal TOUCHVALUE { get; set; }
        public string EnteredBy { get; set; }
        public System.DateTime LastUpdateDate { get; set; }
    }
}
