//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFATERPWebApplication.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class CurrencyMaster
    {
        public int RecordKey { get; set; }
        public decimal Codex { get; set; }
        public string Name { get; set; }
        public string CurSign { get; set; }
        public string Code { get; set; }
        public string CurDecName { get; set; }
        public string Fraction { get; set; }
        public decimal CurDec { get; set; }
        public decimal CurrRate { get; set; }
        public string PostCodeG { get; set; }
        public string PostCodeL { get; set; }
        public decimal TOUCHVALUE { get; set; }
        public string EnteredBy { get; set; }
        public System.DateTime LastUpdateDate { get; set; }
        public string AUTHORISE { get; set; }
        public string AUTHIDS { get; set; }
        public string HWSERIAL { get; set; }
        public string HWSERIAL2 { get; set; }
    }
}
