//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFATERPWebApplication.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemClass
    {
        public int RecordKey { get; set; }
        public string AuthIds { get; set; }
        public string Authorise { get; set; }
        public string Class { get; set; }
        public string Code { get; set; }
        public string HWSerial { get; set; }
        public string HWSerial2 { get; set; }
        public decimal TOUCHVALUE { get; set; }
        public string EnteredBy { get; set; }
        public System.DateTime LastUpdateDate { get; set; }
    }
}
