//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFATERPWebApplication.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemGroup
    {
        public int RecordKey { get; set; }
        public string AcCode { get; set; }
        public string AcCodeX { get; set; }
        public string AcType { get; set; }
        public string BaseGr { get; set; }
        public string Code { get; set; }
        public string Flag { get; set; }
        public string Grp { get; set; }
        public bool Hide { get; set; }
        public bool IsLast { get; set; }
        public bool IsPrefixCode { get; set; }
        public bool IsPrefixDescr { get; set; }
        public int LeadTime { get; set; }
        public string Name { get; set; }
        public string Prefix { get; set; }
        public decimal PurchDisc { get; set; }
        public decimal PurchPer { get; set; }
        public decimal PurchRate { get; set; }
        public string PurchTaxCode { get; set; }
        public decimal SalesDisc { get; set; }
        public decimal SalesMargin { get; set; }
        public decimal SalesMaxDisc { get; set; }
        public decimal SalesPer { get; set; }
        public decimal SalesRate { get; set; }
        public string SalesTaxCode { get; set; }
        public string Unit { get; set; }
        public decimal TOUCHVALUE { get; set; }
        public string EnteredBy { get; set; }
        public System.DateTime LastUpdateDate { get; set; }
        public string AUTHORISE { get; set; }
        public string AUTHIDS { get; set; }
        public string HWSERIAL { get; set; }
        public string HWSERIAL2 { get; set; }
    }
}
