//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFATERPWebApplication.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemBOMRoute
    {
        public int RecordKey { get; set; }
        public string BOMCode { get; set; }
        public string BOMSrl { get; set; }
        public string Code { get; set; }
        public decimal Qty { get; set; }
        public decimal QtyPercent { get; set; }
        public string RouteCode { get; set; }
        public string Sno { get; set; }
        public int Stage { get; set; }
        public decimal TOUCHVALUE { get; set; }
        public string EnteredBy { get; set; }
        public System.DateTime LastUpdateDate { get; set; }
        public string AUTHORISE { get; set; }
        public string AUTHIDS { get; set; }
        public string HWSERIAL { get; set; }
        public string HWSERIAL2 { get; set; }
    
        public virtual ItemBOMHeader ItemBOMHeader { get; set; }
        public virtual ItemBOMHeader ItemBOMHeader1 { get; set; }
        public virtual ItemBOMHeader ItemBOMHeader2 { get; set; }
        public virtual ItemBOMRoute ItemBOMRoute1 { get; set; }
        public virtual ItemBOMRoute ItemBOMRoute2 { get; set; }
    }
}
