//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFATERPWebApplication.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemMore
    {
        public int RecordKey { get; set; }
        public decimal AbtRate { get; set; }
        public decimal ADC { get; set; }
        public string AllowedPack { get; set; }
        public string AltItem { get; set; }
        public string AssetCategory { get; set; }
        public decimal AssRate { get; set; }
        public decimal BatchSize { get; set; }
        public decimal BCD { get; set; }
        public decimal BCDAmt { get; set; }
        public string Category { get; set; }
        public decimal Cess { get; set; }
        public bool ChargesOnQty2 { get; set; }
        public string Code { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public decimal CurrYearExc { get; set; }
        public decimal ExcRate { get; set; }
        public string GoodsHSN { get; set; }
        public decimal GRNProcTime { get; set; }
        public string GroupTree { get; set; }
        public decimal GrWeight { get; set; }
        public decimal GSIRate { get; set; }
        public string Hazard { get; set; }
        public decimal Humidity { get; set; }
        public int iHeight { get; set; }
        public int iLength { get; set; }
        public int iWidth { get; set; }
        public System.DateTime LastUpdateOn { get; set; }
        public decimal LCharges { get; set; }
        public decimal MaxLoad { get; set; }
        public decimal MCharges { get; set; }
        public bool MRPbase { get; set; }
        public string MRPControlGroup { get; set; }
        public string MRPIPType { get; set; }
        public string MRPISType { get; set; }
        public bool MRPReqd { get; set; }
        public string MRPWOType { get; set; }
        public decimal NCCDRate { get; set; }
        public decimal NetWeight { get; set; }
        public decimal NextYearExc { get; set; }
        public decimal OCharges { get; set; }
        public decimal oDuty1 { get; set; }
        public decimal oDuty2 { get; set; }
        public decimal oDuty3 { get; set; }
        public decimal oDutyAmt1 { get; set; }
        public decimal oDutyAmt2 { get; set; }
        public decimal oDutyAmt3 { get; set; }
        public string PackingPlan { get; set; }
        public decimal PackingSize { get; set; }
        public int pHeight { get; set; }
        public string PicturePath { get; set; }
        public int pLength { get; set; }
        public string Potency { get; set; }
        public string PUPrefix { get; set; }
        public int pWidth { get; set; }
        public string QtyEqsn { get; set; }
        public decimal SEDRate { get; set; }
        public decimal SHECess { get; set; }
        public string StockistID { get; set; }
        public decimal Storage { get; set; }
        public string Tariff { get; set; }
        public string TariffGrp { get; set; }
        public decimal Temperature { get; set; }
        public decimal TTARate { get; set; }
        public string UnitDim { get; set; }
        public string UnitMaxLoad { get; set; }
        public string UnitWt { get; set; }
        public decimal TOUCHVALUE { get; set; }
        public string EnteredBy { get; set; }
        public System.DateTime LastUpdateDate { get; set; }
        public string AUTHORISE { get; set; }
        public string AUTHIDS { get; set; }
        public string HWSERIAL { get; set; }
        public string HWSERIAL2 { get; set; }
    }
}
