//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFATERPWebApplication.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemBOM
    {
        public int RecordKey { get; set; }
        public bool AddTolerance { get; set; }
        public bool AllowPartial { get; set; }
        public string AuthIds { get; set; }
        public string Authorise { get; set; }
        public bool BasedQty2 { get; set; }
        public string BomCode { get; set; }
        public string BomSrl { get; set; }
        public decimal ChgAmt1 { get; set; }
        public decimal ChgAmt2 { get; set; }
        public decimal ChgAmt3 { get; set; }
        public string ChildBOM { get; set; }
        public string Code { get; set; }
        public string ECNumber { get; set; }
        public System.DateTime EffectiveDate { get; set; }
        public System.DateTime EffectiveDateTo { get; set; }
        public double Factor { get; set; }
        public bool Fixed { get; set; }
        public string Flag { get; set; }
        public bool FlagCost { get; set; }
        public bool FlagJob { get; set; }
        public bool FlagMFG { get; set; }
        public bool FlagPlan { get; set; }
        public bool FlagPM { get; set; }
        public bool FlagSales { get; set; }
        public string HWSerial { get; set; }
        public string HWSerial2 { get; set; }
        public bool IsSubstitute { get; set; }
        public string ItemCategory { get; set; }
        public decimal LabourAmt { get; set; }
        public decimal Loss { get; set; }
        public bool LossOnWaste { get; set; }
        public decimal MachineAmt { get; set; }
        public bool MfgProcess { get; set; }
        public bool MfgStore { get; set; }
        public bool MultiLevel { get; set; }
        public bool MultiProd { get; set; }
        public decimal OtherAmt { get; set; }
        public string PerUnit { get; set; }
        public decimal pLoss { get; set; }
        public decimal pQty { get; set; }
        public string ProcessCode { get; set; }
        public bool ProductMfg { get; set; }
        public decimal pWastage { get; set; }
        public decimal Qty { get; set; }
        public decimal Qty2 { get; set; }
        public short QtyBasis { get; set; }
        public string QtyEqsn { get; set; }
        public decimal QtyPer { get; set; }
        public string Sno { get; set; }
        public short StockType { get; set; }
        public string Store { get; set; }
        public string SubstituteWith { get; set; }
        public string Unit { get; set; }
        public string Unit2 { get; set; }
        public decimal Wastage { get; set; }
        public string WasteCode { get; set; }
        public string WasteStore { get; set; }
        public decimal TOUCHVALUE { get; set; }
        public string EnteredBy { get; set; }
        public System.DateTime LastUpdateDate { get; set; }
    
        public virtual ItemBOM ItemBOM1 { get; set; }
        public virtual ItemBOM ItemBOM2 { get; set; }
    }
}
