//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFATERPWebApplication.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemBOMHeader
    {
        public ItemBOMHeader()
        {
            this.Stocks = new HashSet<Stock>();
        }
    
        public int RecordKey { get; set; }
        public decimal BatchQty { get; set; }
        public string BOMName { get; set; }
        public string BOMSrl { get; set; }
        public bool BOMType { get; set; }
        public string Code { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime EffectiveDate { get; set; }
        public System.DateTime EffectiveDateTo { get; set; }
        public bool ExcludeKitParent { get; set; }
        public bool ExpandKIT { get; set; }
        public bool IsKIT { get; set; }
        public string LastUpdateBy { get; set; }
        public System.DateTime LastUpdateOn { get; set; }
        public string OrdNumber { get; set; }
        public string Party { get; set; }
        public decimal StdWeight { get; set; }
        public decimal StdYield { get; set; }
        public decimal TOUCHVALUE { get; set; }
        public string EnteredBy { get; set; }
        public System.DateTime LastUpdateDate { get; set; }
        public string AUTHORISE { get; set; }
        public string AUTHIDS { get; set; }
        public string HWSERIAL { get; set; }
        public string HWSERIAL2 { get; set; }
    
        public virtual ItemBOMHeader ItemBOMHeader1 { get; set; }
        public virtual ItemBOMHeader ItemBOMHeader2 { get; set; }
        public virtual ItemBOMRoute ItemBOMRoute { get; set; }
        public virtual ItemBOMRoute ItemBOMRoute1 { get; set; }
        public virtual ItemBOMRoute ItemBOMRoute2 { get; set; }
        public virtual ICollection<Stock> Stocks { get; set; }
    }
}
