//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFATERPWebApplication.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemMaster
    {
        public ItemMaster()
        {
            this.Stocks = new HashSet<Stock>();
        }
    
        public int RecordKey { get; set; }
        public string AcType { get; set; }
        public string AppBranch { get; set; }
        public string AuthIds { get; set; }
        public string Authorise { get; set; }
        public string BarCode { get; set; }
        public string BaseGr { get; set; }
        public bool BomExist { get; set; }
        public string Code { get; set; }
        public string Flag { get; set; }
        public string Grp { get; set; }
        public bool Hide { get; set; }
        public string HWSerial { get; set; }
        public string HWSerial2 { get; set; }
        public bool IsLast { get; set; }
        public bool IsPacking { get; set; }
        public string Name { get; set; }
        public string Narr { get; set; }
        public string PopupMsg { get; set; }
        public string Prefix { get; set; }
        public decimal RedemptionCost { get; set; }
        public short Stocking { get; set; }
        public decimal TouchValue { get; set; }
        public string Unit { get; set; }
        public string EnteredBy { get; set; }
        public System.DateTime LastUpdateDate { get; set; }
    
        public virtual ICollection<Stock> Stocks { get; set; }
    }
}
