//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFATERPWebApplication.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemWarranty
    {
        public int RecordKey { get; set; }
        public decimal AMCChgs { get; set; }
        public string Branch { get; set; }
        public decimal CallChgs { get; set; }
        public string Code { get; set; }
        public bool FreeLabour { get; set; }
        public bool FreeParts { get; set; }
        public int FreeService { get; set; }
        public decimal MinCharges { get; set; }
        public bool OnSite { get; set; }
        public short Pickup { get; set; }
        public string Principle { get; set; }
        public string SCentreNo { get; set; }
        public bool ServiceCard { get; set; }
        public bool ServiceSch { get; set; }
        public int Warranty { get; set; }
        public string WarrantyCover { get; set; }
        public string WarrantyNote { get; set; }
        public bool WarrantyPart { get; set; }
        public decimal TOUCHVALUE { get; set; }
        public string EnteredBy { get; set; }
        public System.DateTime LastUpdateDate { get; set; }
        public string AUTHORISE { get; set; }
        public string AUTHIDS { get; set; }
        public string HWSERIAL { get; set; }
        public string HWSERIAL2 { get; set; }
    }
}
