//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFATERPWebApplication.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class LCMaster
    {
        public int RecordKey { get; set; }
        public string Branch { get; set; }
        public string CurName { get; set; }
        public decimal CurRate { get; set; }
        public string DiscBy { get; set; }
        public decimal DiscChg { get; set; }
        public System.DateTime FDDate { get; set; }
        public System.DateTime FDDueDate { get; set; }
        public string FDNo { get; set; }
        public string IntBy { get; set; }
        public decimal IntChg { get; set; }
        public decimal LCAmount { get; set; }
        public System.DateTime LCDate { get; set; }
        public System.DateTime LCDueDate { get; set; }
        public string LCNo { get; set; }
        public decimal LCOpnChg { get; set; }
        public string LCType { get; set; }
        public decimal MarginMoney { get; set; }
        public string Narr { get; set; }
        public string Party { get; set; }
        public string PInvNo { get; set; }
        public System.DateTime RevDate { get; set; }
        public string RevNarr { get; set; }
        public string RevNo { get; set; }
        public decimal TouchValue { get; set; }
        public string EnteredBy { get; set; }
        public System.DateTime LastUpdateDate { get; set; }
        public string AUTHORISE { get; set; }
        public string AUTHIDS { get; set; }
        public string HWSERIAL { get; set; }
        public string HWSERIAL2 { get; set; }
    }
}
