//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFATERPWebApplication.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ledger
    {
        public int RecordKey { get; set; }
        public string AccPeriod { get; set; }
        public string Allocation { get; set; }
        public string AltCode { get; set; }
        public bool Audited { get; set; }
        public string AuthIds { get; set; }
        public string Authorise { get; set; }
        public string BankCode { get; set; }
        public System.DateTime BillDate { get; set; }
        public string BillNumber { get; set; }
        public string Branch { get; set; }
        public string Cheque { get; set; }
        public bool ChequeReturn { get; set; }
        public short ChqCategory { get; set; }
        public System.DateTime ClearDate { get; set; }
        public string Code { get; set; }
        public string CostCentre { get; set; }
        public decimal Credit { get; set; }
        public int CrPeriod { get; set; }
        public decimal CurrAmount { get; set; }
        public string CurrName { get; set; }
        public decimal CurrRate { get; set; }
        public decimal Debit { get; set; }
        public bool Discounted { get; set; }
        public string Division { get; set; }
        public System.DateTime DocDate { get; set; }
        public string HWSerial { get; set; }
        public string HWSerial2 { get; set; }
        public string MainType { get; set; }
        public string Narr { get; set; }
        public string Party { get; set; }
        public string PCCode { get; set; }
        public string PeriodCode { get; set; }
        public string Prefix { get; set; }
        public string ProjectCode { get; set; }
        public string ProjectStage { get; set; }
        public string ProjectUnit { get; set; }
        public string RecoFlag { get; set; }
        public string RefDoc { get; set; }
        public string SLCode { get; set; }
        public string Sno { get; set; }
        public string Srl { get; set; }
        public string SubType { get; set; }
        public string TDSChallanNumber { get; set; }
        public string TDSCode { get; set; }
        public bool TdsFlag { get; set; }
        public string Type { get; set; }
        public decimal TOUCHVALUE { get; set; }
        public string EnteredBy { get; set; }
        public System.DateTime LastUpdateDate { get; set; }
    
        public virtual TfatPass TfatPass { get; set; }
        public virtual Master Master { get; set; }
        public virtual Master Master1 { get; set; }
        public virtual Master Master2 { get; set; }
        public virtual DocType DocType { get; set; }
        public virtual Sale Sale { get; set; }
        public virtual SalesDivision SalesDivision { get; set; }
        public virtual MainType MainType1 { get; set; }
        public virtual SubLedger SubLedger { get; set; }
        public virtual SubType SubType1 { get; set; }
    }
}
