//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFATERPWebApplication.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class MasterInfo
    {
        public int RecordKey { get; set; }
        public string AcHeadCode { get; set; }
        public decimal AcHeadPerc { get; set; }
        public string AppProduct { get; set; }
        public string Area { get; set; }
        public string AreaTree { get; set; }
        public string Broker { get; set; }
        public decimal Brokerage { get; set; }
        public string BSRCode { get; set; }
        public bool CashDisc { get; set; }
        public bool CheckCRDays { get; set; }
        public bool CheckCRLimit { get; set; }
        public string Code { get; set; }
        public string CompanyType { get; set; }
        public string CostCentre { get; set; }
        public bool CRDaysWarn { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public decimal CrLimit { get; set; }
        public decimal CRLimitTole { get; set; }
        public bool CRLimitWarn { get; set; }
        public bool CRLimitWithPO { get; set; }
        public bool CRLimitWithTrx { get; set; }
        public int CrPeriod { get; set; }
        public string CurrName { get; set; }
        public string DCCode { get; set; }
        public string DepricAC { get; set; }
        public decimal DiscDays { get; set; }
        public decimal DiscPerc { get; set; }
        public string DrAcNo { get; set; }
        public bool EmailParty { get; set; }
        public bool EmailSalesman { get; set; }
        public string EmailTemplate { get; set; }
        public string EmailUsers { get; set; }
        public string Flag { get; set; }
        public short FormDays { get; set; }
        public bool FormFri { get; set; }
        public bool FormMon { get; set; }
        public bool FormSat { get; set; }
        public bool FormSun { get; set; }
        public bool FormThu { get; set; }
        public bool FormTue { get; set; }
        public bool FormWed { get; set; }
        public short FreqForm { get; set; }
        public short FreqOS { get; set; }
        public string Grp { get; set; }
        public string IncoPlace { get; set; }
        public string IncoTerms { get; set; }
        public decimal IntAmt { get; set; }
        public decimal IntRate { get; set; }
        public bool IsLead { get; set; }
        public System.DateTime LastSent { get; set; }
        public string LastUpdateBy { get; set; }
        public System.DateTime LastUpdateOn { get; set; }
        public System.DateTime LeadConvertDt { get; set; }
        public bool LedInner { get; set; }
        public bool LedInnerNarr { get; set; }
        public short LedNarr { get; set; }
        public short LedSummary { get; set; }
        public bool MergeCrLimit { get; set; }
        public string Name { get; set; }
        public string Narr { get; set; }
        public int nFormDays { get; set; }
        public bool NoDetails { get; set; }
        public int nOSDays { get; set; }
        public decimal ODLimit { get; set; }
        public short OSDays { get; set; }
        public bool OSFri { get; set; }
        public bool OSMon { get; set; }
        public bool OSSat { get; set; }
        public bool OSSun { get; set; }
        public bool OSThu { get; set; }
        public bool OSTue { get; set; }
        public bool OSWed { get; set; }
        public string PaymentTerms { get; set; }
        public string ReminderFormat { get; set; }
        public string RTGS { get; set; }
        public string SalesMan { get; set; }
        public bool SMSParty { get; set; }
        public bool SMSSalesman { get; set; }
        public string SMSTemplate { get; set; }
        public string SMSUsers { get; set; }
        public string Transporter { get; set; }
        public string xBranch { get; set; }
        public decimal TOUCHVALUE { get; set; }
        public string EnteredBy { get; set; }
        public System.DateTime LastUpdateDate { get; set; }
        public string AUTHORISE { get; set; }
        public string AUTHIDS { get; set; }
        public string HWSERIAL { get; set; }
        public string HWSERIAL2 { get; set; }
    }
}
