//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFATERPWebApplication.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Master1
    {
        public int RecordKey { get; set; }
        public string AcType { get; set; }
        public string AppBranch { get; set; }
        public bool ARAP { get; set; }
        public string Area { get; set; }
        public string AuthIds { get; set; }
        public string Authorise { get; set; }
        public bool AutoEmail { get; set; }
        public bool AutoSMS { get; set; }
        public string BaseGr { get; set; }
        public string Broker { get; set; }
        public string Category { get; set; }
        public bool CCBudget { get; set; }
        public bool CCReqd { get; set; }
        public string Code { get; set; }
        public string CostCentre { get; set; }
        public bool CutTDS { get; set; }
        public decimal DftAddress { get; set; }
        public int ExcType { get; set; }
        public string Flag { get; set; }
        public bool ForceCC { get; set; }
        public string Grp { get; set; }
        public bool Hide { get; set; }
        public string HWSerial { get; set; }
        public string HWSerial2 { get; set; }
        public bool IsLast { get; set; }
        public bool IsPublic { get; set; }
        public bool IsSubLedger { get; set; }
        public string Name { get; set; }
        public bool NonActive { get; set; }
        public string PCCode { get; set; }
        public byte Rank { get; set; }
        public string RevGroup { get; set; }
        public string Salesman { get; set; }
        public string ShortName { get; set; }
        public string StringValue { get; set; }
        public string TDSCode { get; set; }
        public decimal TouchValue { get; set; }
        public string UserID { get; set; }
        public string EnteredBy { get; set; }
        public System.DateTime LastUpdateDate { get; set; }
        public bool IsLead { get; set; }
        public string LeadCode { get; set; }
        public System.DateTime LeadConvertDt { get; set; }
        public string AcHeadCode { get; set; }
        public decimal AcHeadPerc { get; set; }
        public string AliasPrefix { get; set; }
        public string AppProduct { get; set; }
        public string AreaTree { get; set; }
        public decimal Brokerage { get; set; }
        public string BSRCode { get; set; }
        public bool CashDisc { get; set; }
        public string CompanyType { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string DepricAC { get; set; }
        public decimal DiscDays { get; set; }
        public decimal DiscPerc { get; set; }
        public int DisplayOrder { get; set; }
        public bool FBT { get; set; }
        public string FBTCode { get; set; }
        public decimal FBTRate { get; set; }
        public decimal FBTSlab { get; set; }
        public decimal IntAmt { get; set; }
        public decimal IntRate { get; set; }
        public bool IsChanged { get; set; }
        public string LastUpdateBy { get; set; }
        public System.DateTime LastUpdateOn { get; set; }
        public bool LedInner { get; set; }
        public bool LedInnerNarr { get; set; }
        public short LedNarr { get; set; }
        public short LedSummary { get; set; }
        public bool MergeCrLimit { get; set; }
        public bool NoDetails { get; set; }
        public decimal Opening { get; set; }
        public string PaymentTerms { get; set; }
        public string Sch { get; set; }
        public bool ServiceTax { get; set; }
        public string ServiceTaxCode { get; set; }
        public decimal TotalCredit { get; set; }
        public decimal TotalDebit { get; set; }
        public string Transporter { get; set; }
        public string xBranch { get; set; }
    }
}
