//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFATERPWebApplication.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class MasterGroup
    {
        public int RecordKey { get; set; }
        public string AcType { get; set; }
        public string AliasPrefix { get; set; }
        public string BaseGr { get; set; }
        public string Code { get; set; }
        public string CostCentre { get; set; }
        public int DisplayOrder { get; set; }
        public bool ForceCC { get; set; }
        public string Grp { get; set; }
        public bool Hide { get; set; }
        public bool IsLast { get; set; }
        public int Level { get; set; }
        public string Name { get; set; }
        public bool NoDetails { get; set; }
        public string PCCode { get; set; }
        public string RevGroup { get; set; }
        public string Sch { get; set; }
        public int Seq { get; set; }
        public string StructureCode { get; set; }
        public decimal TOUCHVALUE { get; set; }
        public string EnteredBy { get; set; }
        public System.DateTime LastUpdateDate { get; set; }
        public string AUTHORISE { get; set; }
        public string AUTHIDS { get; set; }
        public string HWSERIAL { get; set; }
        public string HWSERIAL2 { get; set; }
    }
}
