//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFATERPWebApplication.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentTerm
    {
        public int RecordKey { get; set; }
        public bool BillCycle { get; set; }
        public int BillFrom { get; set; }
        public int BillsNos { get; set; }
        public int BillTo { get; set; }
        public bool CheckNos { get; set; }
        public string Code { get; set; }
        public int CrPeriod { get; set; }
        public int Days { get; set; }
        public int Grace { get; set; }
        public string Name { get; set; }
        public string Narr { get; set; }
        public bool PayCash { get; set; }
        public decimal Percentage { get; set; }
        public bool RestViolate { get; set; }
        public string Type { get; set; }
        public decimal TOUCHVALUE { get; set; }
        public string EnteredBy { get; set; }
        public System.DateTime LastUpdateDate { get; set; }
        public string AUTHORISE { get; set; }
        public string AUTHIDS { get; set; }
        public string HWSERIAL { get; set; }
        public string HWSERIAL2 { get; set; }
        public string PostD { get; set; }
        public string PostI { get; set; }
    }
}
