//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFATERPWebApplication.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProcessMas1
    {
        public int RecordKey { get; set; }
        public string AuthIds { get; set; }
        public string Authorise { get; set; }
        public decimal BatchQty { get; set; }
        public string Code { get; set; }
        public int CrewSize { get; set; }
        public System.DateTime EffDate { get; set; }
        public bool GeneratePO { get; set; }
        public string HWSerial { get; set; }
        public decimal LabourHour { get; set; }
        public string Machine { get; set; }
        public decimal MachineHour { get; set; }
        public bool MasterProcess { get; set; }
        public string MCSerial { get; set; }
        public decimal MoveHour { get; set; }
        public string Name { get; set; }
        public string NextProcess { get; set; }
        public string NextStore { get; set; }
        public bool NoBatch { get; set; }
        public string ProcessCode { get; set; }
        public string ProcessItem { get; set; }
        public string ProcessType { get; set; }
        public bool QCReqd { get; set; }
        public decimal QueueHour { get; set; }
        public string ReasonType { get; set; }
        public decimal SetupHour { get; set; }
        public string Store { get; set; }
        public System.DateTime UnitTime { get; set; }
        public string WorkStation { get; set; }
        public decimal Yield { get; set; }
        public decimal TOUCHVALUE { get; set; }
        public string EnteredBy { get; set; }
        public System.DateTime LastUpdateDate { get; set; }
        public string HWSERIAL2 { get; set; }
    }
}
