//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFATERPWebApplication.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectDetail
    {
        public int RecordKey { get; set; }
        public System.DateTime AccStartDate { get; set; }
        public System.DateTime ActualFinishDate { get; set; }
        public System.DateTime ActualStartDate { get; set; }
        public string Adrl1 { get; set; }
        public string Adrl2 { get; set; }
        public string Adrl3 { get; set; }
        public string Area { get; set; }
        public decimal BonusAmt { get; set; }
        public decimal BonusMax { get; set; }
        public string BonusPeriodType { get; set; }
        public string Broker { get; set; }
        public decimal BuildArea { get; set; }
        public decimal Buildings { get; set; }
        public decimal BuiltupArea { get; set; }
        public int BussinessType { get; set; }
        public decimal CarpetArea { get; set; }
        public decimal ChargeableArea { get; set; }
        public string City { get; set; }
        public string CityGrade { get; set; }
        public string ClientTemp { get; set; }
        public string Code { get; set; }
        public string ContDescr { get; set; }
        public decimal ContPeriod { get; set; }
        public int ContPeriodStart { get; set; }
        public string ContPeriodType { get; set; }
        public string ContractorTemp { get; set; }
        public decimal ContractValue { get; set; }
        public string Country { get; set; }
        public int DefectLiabDays { get; set; }
        public decimal DelayPenalty { get; set; }
        public decimal DelayPenaltyMax { get; set; }
        public string DelayPenaltyType { get; set; }
        public string Designation { get; set; }
        public bool Drainage { get; set; }
        public bool Electricity { get; set; }
        public string Email { get; set; }
        public decimal EmdAmt { get; set; }
        public bool Escalation { get; set; }
        public int EscDays { get; set; }
        public System.DateTime EstFinishDate { get; set; }
        public System.DateTime EstStartDate { get; set; }
        public string Flag { get; set; }
        public int Flats { get; set; }
        public decimal Floors { get; set; }
        public decimal FSIIndex { get; set; }
        public bool GasLine { get; set; }
        public bool Generator { get; set; }
        public short GrndWater { get; set; }
        public string Grp { get; set; }
        public decimal GuideLineValue { get; set; }
        public bool Hide { get; set; }
        public string Images { get; set; }
        public bool IsFinalUnit { get; set; }
        public decimal LandArea { get; set; }
        public decimal LandRate { get; set; }
        public decimal LIQDamage { get; set; }
        public bool Locked { get; set; }
        public decimal MobAdv { get; set; }
        public decimal MobAdvLimit { get; set; }
        public int MobAdvRABill { get; set; }
        public string Mobile { get; set; }
        public string Name { get; set; }
        public string Party { get; set; }
        public decimal Penalty { get; set; }
        public string Person { get; set; }
        public string Pin { get; set; }
        public string PrjStatus { get; set; }
        public int ProjectType { get; set; }
        public decimal RegValue { get; set; }
        public decimal Retention { get; set; }
        public decimal RetentionRelease { get; set; }
        public decimal SalesRate { get; set; }
        public decimal SalesRateAdd { get; set; }
        public int SalesRateAddFloor { get; set; }
        public string ScopeOfWork { get; set; }
        public decimal SDAmt { get; set; }
        public string SerTaxCode { get; set; }
        public string SoilType { get; set; }
        public int State { get; set; }
        public string TaxCode { get; set; }
        public string Telephone { get; set; }
        public string TrType { get; set; }
        public bool Vastushastra { get; set; }
        public bool WaterSupply { get; set; }
        public decimal Wings { get; set; }
        public decimal WorkArea { get; set; }
        public decimal WorkChargeArea { get; set; }
        public decimal WorkRate { get; set; }
        public decimal TOUCHVALUE { get; set; }
        public string EnteredBy { get; set; }
        public System.DateTime LastUpdateDate { get; set; }
        public string AUTHORISE { get; set; }
        public string AUTHIDS { get; set; }
        public string HWSERIAL { get; set; }
        public string HWSERIAL2 { get; set; }
    
        public virtual Master Master { get; set; }
        public virtual TfatState TfatState { get; set; }
        public virtual TaxMaster TaxMaster { get; set; }
    }
}
