//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFATERPWebApplication.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportHeader
    {
        public int RecordKey { get; set; }
        public bool AllowEmail { get; set; }
        public bool AllowSMS { get; set; }
        public string BackColor { get; set; }
        public string Code { get; set; }
        public string Comp { get; set; }
        public bool DefaultReport { get; set; }
        public bool DisplayGrid { get; set; }
        public decimal Divisor { get; set; }
        public string DrillCaption { get; set; }
        public string DrillQuery { get; set; }
        public string DrillQuerySub { get; set; }
        public string EMAILTemplate { get; set; }
        public string EnteredBy { get; set; }
        public bool FontBold { get; set; }
        public bool FontItalics { get; set; }
        public string FontName { get; set; }
        public short FontSize { get; set; }
        public bool FontStrike { get; set; }
        public bool FontUnderLine { get; set; }
        public string ForeColor { get; set; }
        public string FormatGroup { get; set; }
        public string FormatHead { get; set; }
        public int GridColor { get; set; }
        public string GroupHead { get; set; }
        public int HeaderHeight { get; set; }
        public decimal LabelHORNos { get; set; }
        public decimal LabelHORSpace { get; set; }
        public bool LabelOption { get; set; }
        public short LabelPrintTitle { get; set; }
        public decimal LabelTitleWidth { get; set; }
        public decimal LabelVERNos { get; set; }
        public decimal LabelVERSpace { get; set; }
        public System.DateTime LastUpdateDate { get; set; }
        public bool Locked { get; set; }
        public string MenuPlace { get; set; }
        public int minHeight { get; set; }
        public string Modules { get; set; }
        public bool NoDetails { get; set; }
        public bool NoSubHeading { get; set; }
        public short OwnReport { get; set; }
        public bool PageOrient { get; set; }
        public bool pBlank { get; set; }
        public string pMerge { get; set; }
        public string PostLogic { get; set; }
        public string pToMerge { get; set; }
        public short RecLines { get; set; }
        public string RecordFilter { get; set; }
        public bool RemoveUnused { get; set; }
        public bool RunAtStart { get; set; }
        public short SepLines { get; set; }
        public bool ShowFilter { get; set; }
        public string SMSTemplate { get; set; }
        public string SortedOn { get; set; }
        public string SubCodeOf { get; set; }
        public bool SubTotal { get; set; }
        public string SubTotalOn { get; set; }
        public bool Summarized { get; set; }
        public string Tables { get; set; }
        public int TimesUsed { get; set; }
        public decimal TouchValue { get; set; }
        public string UserQuery { get; set; }
        public string Users { get; set; }
        public string AUTHORISE { get; set; }
        public string AUTHIDS { get; set; }
        public string HWSERIAL { get; set; }
        public string HWSERIAL2 { get; set; }
    }
}
