//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFATERPWebApplication.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportGroup
    {
        public int RecordKey { get; set; }
        public string Code { get; set; }
        public string Descr { get; set; }
        public string Flag { get; set; }
        public string Grp { get; set; }
        public short Level { get; set; }
        public string Modules { get; set; }
        public decimal Touchvalue { get; set; }
        public string Users { get; set; }
        public string EnteredBy { get; set; }
        public System.DateTime LastUpdateDate { get; set; }
        public string AUTHORISE { get; set; }
        public string AUTHIDS { get; set; }
        public string HWSERIAL { get; set; }
        public string HWSERIAL2 { get; set; }
    }
}
