//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFATERPWebApplication.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class rStock
    {
        public int RecordKey { get; set; }
        public string AccPeriod { get; set; }
        public decimal Amt { get; set; }
        public string Bearer { get; set; }
        public string BillNo { get; set; }
        public bool BomItem { get; set; }
        public string Branch { get; set; }
        public string CancelBill { get; set; }
        public bool Canceled { get; set; }
        public string CancelReason { get; set; }
        public string Captain { get; set; }
        public string Code { get; set; }
        public decimal Disc { get; set; }
        public decimal DiscAmt { get; set; }
        public System.DateTime DocDate { get; set; }
        public string DocTime { get; set; }
        public string MainType { get; set; }
        public bool NotInStock { get; set; }
        public string ObjectType { get; set; }
        public int PaxNo { get; set; }
        public string PeriodCode { get; set; }
        public string Prefix { get; set; }
        public string PrepareFlag { get; set; }
        public decimal Qty { get; set; }
        public decimal Rate { get; set; }
        public string Remark { get; set; }
        public string ServiceType { get; set; }
        public int Sno { get; set; }
        public string Srl { get; set; }
        public string Store { get; set; }
        public string SubType { get; set; }
        public string TableCode { get; set; }
        public string TaxCode { get; set; }
        public string Type { get; set; }
        public decimal TOUCHVALUE { get; set; }
        public string EnteredBy { get; set; }
        public System.DateTime LastUpdateDate { get; set; }
        public string AUTHORISE { get; set; }
        public string AUTHIDS { get; set; }
        public string HWSERIAL { get; set; }
        public string HWSERIAL2 { get; set; }
    }
}
