//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFATERPWebApplication.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        public Sale()
        {
            this.Attachments = new HashSet<Attachment>();
            this.Ledgers = new HashSet<Ledger>();
            this.AddOnRS = new HashSet<AddOnR>();
        }
    
        public int RecordKey { get; set; }
        public string AccPeriod { get; set; }
        public string AcHeadCode { get; set; }
        public decimal AcHeadPerc { get; set; }
        public decimal AddTax { get; set; }
        public short AltAddress { get; set; }
        public decimal Amt { get; set; }
        public decimal Amt1 { get; set; }
        public decimal Amt2 { get; set; }
        public decimal Amt3 { get; set; }
        public decimal AssAmt { get; set; }
        public string AuthIds { get; set; }
        public string Authorise { get; set; }
        public System.DateTime BillDate { get; set; }
        public string BillNumber { get; set; }
        public bool BomUpdated { get; set; }
        public string Branch { get; set; }
        public string Broker { get; set; }
        public decimal Brokerage { get; set; }
        public decimal BrokerAmt { get; set; }
        public decimal BrokerOn { get; set; }
        public decimal CardAmt { get; set; }
        public string CardNumber { get; set; }
        public decimal CashAmt { get; set; }
        public decimal Cess { get; set; }
        public System.DateTime ChlnDate { get; set; }
        public string ChlnNumber { get; set; }
        public decimal ChqAmt { get; set; }
        public string ChqNo { get; set; }
        public string Code { get; set; }
        public string CostCentre { get; set; }
        public bool Coupan { get; set; }
        public string CouponNumber { get; set; }
        public decimal CrCardAmt { get; set; }
        public string CrCardNo { get; set; }
        public decimal CreditAmt { get; set; }
        public int CrPeriod { get; set; }
        public decimal CurrAmount { get; set; }
        public string CurrName { get; set; }
        public decimal CurrRate { get; set; }
        public string DCCode { get; set; }
        public string DeliverBy { get; set; }
        public short DelyAltAdd { get; set; }
        public string Delycode { get; set; }
        public System.DateTime DelyDate { get; set; }
        public decimal Disc { get; set; }
        public decimal Discount { get; set; }
        public bool Discounted { get; set; }
        public string Division { get; set; }
        public System.DateTime DocDate { get; set; }
        public decimal ExcAmt { get; set; }
        public string ExcInvNo { get; set; }
        public decimal ExciseAs { get; set; }
        public bool ExciseLess { get; set; }
        public decimal ExcRate { get; set; }
        public decimal FCAmt1 { get; set; }
        public decimal FCAmt2 { get; set; }
        public decimal FCAmt3 { get; set; }
        public string FCCode1 { get; set; }
        public string FCCode2 { get; set; }
        public string FCCode3 { get; set; }
        public bool ForceOrderP { get; set; }
        public string HWSerial { get; set; }
        public string HWSerial2 { get; set; }
        public string IncoPlace { get; set; }
        public string IncoTerms { get; set; }
        public string ITFNumber { get; set; }
        public string LCNo { get; set; }
        public string MainType { get; set; }
        public string Narr { get; set; }
        public string OrdNumber { get; set; }
        public string PayTerms { get; set; }
        public string PCCode { get; set; }
        public string PeriodCode { get; set; }
        public string PKNumber { get; set; }
        public string Prefix { get; set; }
        public string ProjectCode { get; set; }
        public string ProjectStage { get; set; }
        public string ProjectUnit { get; set; }
        public decimal Qty { get; set; }
        public string ReceiveBy { get; set; }
        public string RefParty { get; set; }
        public string RefSno { get; set; }
        public decimal RoundOff { get; set; }
        public decimal RunBal { get; set; }
        public decimal SalemanAmt { get; set; }
        public decimal SalemanOn { get; set; }
        public decimal SalemanPer { get; set; }
        public string SalesMan { get; set; }
        public string Srl { get; set; }
        public int Stage { get; set; }
        public decimal STAmt { get; set; }
        public decimal Staxable { get; set; }
        public decimal STCess { get; set; }
        public string STCode { get; set; }
        public decimal STSheCess { get; set; }
        public string SubType { get; set; }
        public decimal SurCharge { get; set; }
        public string TaskID { get; set; }
        public decimal Taxable { get; set; }
        public decimal TaxAmt { get; set; }
        public string TaxCode { get; set; }
        public decimal TDSAble { get; set; }
        public decimal TDSAmt { get; set; }
        public decimal TDSCess { get; set; }
        public string TDSCode { get; set; }
        public bool TDSFlag { get; set; }
        public string TDSReason { get; set; }
        public decimal TDSSchg { get; set; }
        public decimal TDSTax { get; set; }
        public string TrackNo { get; set; }
        public string TrayNo { get; set; }
        public string Type { get; set; }
        public decimal Val1 { get; set; }
        public decimal Val2 { get; set; }
        public decimal Val3 { get; set; }
        public string WONumber { get; set; }
        public decimal TOUCHVALUE { get; set; }
        public string EnteredBy { get; set; }
        public System.DateTime LastUpdateDate { get; set; }
    
        public virtual ICollection<Attachment> Attachments { get; set; }
        public virtual DocType DocType { get; set; }
        public virtual IncoTerm IncoTerm { get; set; }
        public virtual ICollection<Ledger> Ledgers { get; set; }
        public virtual MainType MainType1 { get; set; }
        public virtual Master Master { get; set; }
        public virtual Master Master1 { get; set; }
        public virtual ICollection<AddOnR> AddOnRS { get; set; }
        public virtual TfatPass TfatPass { get; set; }
        public virtual SalesChannel SalesChannel { get; set; }
        public virtual SalesDivision SalesDivision { get; set; }
        public virtual SalesMan SalesMan1 { get; set; }
        public virtual SubType SubType1 { get; set; }
        public virtual TaxMaster TaxMaster { get; set; }
        public virtual ServiceTaxMaster ServiceTaxMaster { get; set; }
    }
}
