//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFATERPWebApplication.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesTaxDetail
    {
        public int RecordKey { get; set; }
        public string AccPeriod { get; set; }
        public double AddTax { get; set; }
        public double AddTax2 { get; set; }
        public decimal Amt { get; set; }
        public double aSurcharge { get; set; }
        public string Branch { get; set; }
        public decimal Cess { get; set; }
        public string Code { get; set; }
        public string CurrName { get; set; }
        public decimal CurrRate { get; set; }
        public System.DateTime DocDate { get; set; }
        public string MainType { get; set; }
        public bool NotInStock { get; set; }
        public string Party { get; set; }
        public string PeriodCode { get; set; }
        public string Prefix { get; set; }
        public string Sno { get; set; }
        public string Srl { get; set; }
        public string SubType { get; set; }
        public double SurCharge { get; set; }
        public double Taxable { get; set; }
        public double TaxAmt { get; set; }
        public string TaxCode { get; set; }
        public string Type { get; set; }
        public decimal TOUCHVALUE { get; set; }
        public string EnteredBy { get; set; }
        public System.DateTime LastUpdateDate { get; set; }
        public string AUTHORISE { get; set; }
        public string AUTHIDS { get; set; }
        public string HWSERIAL { get; set; }
        public string HWSERIAL2 { get; set; }
    }
}
