//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFATERPWebApplication.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesMan
    {
        public SalesMan()
        {
            this.Masters = new HashSet<Master>();
            this.Sales = new HashSet<Sale>();
            this.SalesMan1 = new HashSet<SalesMan>();
        }
    
        public int RecordKey { get; set; }
        public string Adrl1 { get; set; }
        public string Adrl2 { get; set; }
        public string Adrl3 { get; set; }
        public string Area { get; set; }
        public string AuthIds { get; set; }
        public string Authorise { get; set; }
        public System.DateTime BirthDate { get; set; }
        public string Category { get; set; }
        public string City { get; set; }
        public string Code { get; set; }
        public decimal Comm { get; set; }
        public string CorpID { get; set; }
        public string Country { get; set; }
        public string Designation { get; set; }
        public string Email { get; set; }
        public string Flag { get; set; }
        public string Grp { get; set; }
        public bool Hide { get; set; }
        public string HWSerial { get; set; }
        public string HWSerial2 { get; set; }
        public string InOutFlag { get; set; }
        public short Level { get; set; }
        public bool Locked { get; set; }
        public string LowerList { get; set; }
        public bool Member { get; set; }
        public string Mobile { get; set; }
        public string Name { get; set; }
        public System.DateTime OutTime { get; set; }
        public string Password { get; set; }
        public string Pin { get; set; }
        public int State { get; set; }
        public string Telephone { get; set; }
        public string UserID { get; set; }
        public decimal TOUCHVALUE { get; set; }
        public string EnteredBy { get; set; }
        public System.DateTime LastUpdateDate { get; set; }
    
        public virtual ICollection<Master> Masters { get; set; }
        public virtual ICollection<Sale> Sales { get; set; }
        public virtual ICollection<SalesMan> SalesMan1 { get; set; }
        public virtual SalesMan SalesMan2 { get; set; }
        public virtual TfatState TfatState { get; set; }
    }
}
