//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFATERPWebApplication.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Scheme
    {
        public int RecordKey { get; set; }
        public bool Active { get; set; }
        public string AuthIds { get; set; }
        public string Authorise { get; set; }
        public string Branch { get; set; }
        public bool CashHalf { get; set; }
        public string Code { get; set; }
        public decimal Discount { get; set; }
        public decimal DiscPercent { get; set; }
        public bool DiscPerQty { get; set; }
        public string Flag { get; set; }
        public bool FreeOrDisc { get; set; }
        public string FreeProd { get; set; }
        public decimal FreeQty { get; set; }
        public System.DateTime FromDt { get; set; }
        public string HWSerial { get; set; }
        public string HWSerial2 { get; set; }
        public decimal MinQty { get; set; }
        public string Party { get; set; }
        public bool PartyScheme { get; set; }
        public string Product { get; set; }
        public decimal Qty { get; set; }
        public string Scheme1 { get; set; }
        public System.DateTime ToDt { get; set; }
        public decimal TOUCHVALUE { get; set; }
        public string EnteredBy { get; set; }
        public System.DateTime LastUpdateDate { get; set; }
    }
}
