//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFATERPWebApplication.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceTaxRate
    {
        public int RecordKey { get; set; }
        public decimal Abatement { get; set; }
        public string Code { get; set; }
        public System.DateTime EffDate { get; set; }
        public string Notification { get; set; }
        public decimal STCess { get; set; }
        public string STCessPost { get; set; }
        public decimal STRate { get; set; }
        public string STRatePost { get; set; }
        public decimal STSheCess { get; set; }
        public string STSheCessPost { get; set; }
        public decimal TOUCHVALUE { get; set; }
        public string EnteredBy { get; set; }
        public System.DateTime LastUpdateDate { get; set; }
        public string AUTHORISE { get; set; }
        public string AUTHIDS { get; set; }
        public string HWSERIAL { get; set; }
        public string HWSERIAL2 { get; set; }
    }
}
