//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFATERPWebApplication.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceTaxMaster
    {
        public ServiceTaxMaster()
        {
            this.Sales = new HashSet<Sale>();
            this.Stocks = new HashSet<Stock>();
        }
    
        public int RecordKey { get; set; }
        public string AccCode { get; set; }
        public string CategoryCode { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string STCessPost { get; set; }
        public string STCessPostR { get; set; }
        public string STRatePost { get; set; }
        public string STRatePostR { get; set; }
        public string STSheCessPost { get; set; }
        public string STSheCessPostR { get; set; }
        public string SubClause { get; set; }
        public decimal TOUCHVALUE { get; set; }
        public string EnteredBy { get; set; }
        public System.DateTime LastUpdateDate { get; set; }
        public string AUTHORISE { get; set; }
        public string AUTHIDS { get; set; }
        public string HWSERIAL { get; set; }
        public string HWSERIAL2 { get; set; }
    
        public virtual Master Master { get; set; }
        public virtual Master Master1 { get; set; }
        public virtual Master Master2 { get; set; }
        public virtual Master Master3 { get; set; }
        public virtual Master Master4 { get; set; }
        public virtual Master Master5 { get; set; }
        public virtual ICollection<Sale> Sales { get; set; }
        public virtual ICollection<Stock> Stocks { get; set; }
    }
}
