//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFATERPWebApplication.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockExcise
    {
        public int RecordKey { get; set; }
        public decimal AbtRate { get; set; }
        public string AccPeriod { get; set; }
        public decimal ADC { get; set; }
        public decimal ADCAmt { get; set; }
        public decimal AssAmt { get; set; }
        public decimal AssRate { get; set; }
        public decimal AssRt { get; set; }
        public string AuthIds { get; set; }
        public string Authorise { get; set; }
        public decimal BCD { get; set; }
        public decimal BCDAmt { get; set; }
        public decimal BEDAmt { get; set; }
        public System.DateTime BillDate { get; set; }
        public string BillNumber { get; set; }
        public string Branch { get; set; }
        public decimal Cess { get; set; }
        public decimal CessAmt { get; set; }
        public string Code { get; set; }
        public System.DateTime DocDate { get; set; }
        public string ECCode { get; set; }
        public decimal ExcAmt { get; set; }
        public decimal ExcClaim { get; set; }
        public System.DateTime ExcInvDt { get; set; }
        public string ExcInvNo { get; set; }
        public decimal Excise000009968 { get; set; }
        public decimal Excise000009971 { get; set; }
        public decimal Excise000009972 { get; set; }
        public decimal Excise000009973 { get; set; }
        public decimal Excise000009974 { get; set; }
        public decimal Excise000009975 { get; set; }
        public decimal Excise000009978 { get; set; }
        public decimal Excise000009979 { get; set; }
        public decimal Excise000009983 { get; set; }
        public decimal Excise000009984 { get; set; }
        public decimal Excise000009985 { get; set; }
        public decimal Excise000009986 { get; set; }
        public decimal Excise000009987 { get; set; }
        public decimal Excise000009988 { get; set; }
        public decimal Excise000009993 { get; set; }
        public decimal Excise000009995 { get; set; }
        public decimal Excise000009998 { get; set; }
        public decimal Excise000009999 { get; set; }
        public decimal Excise000100000 { get; set; }
        public decimal Excise000100006 { get; set; }
        public decimal Excise000100010 { get; set; }
        public decimal Excise000100011 { get; set; }
        public decimal Excise000100012 { get; set; }
        public decimal Excise000100013 { get; set; }
        public decimal ExciseAs { get; set; }
        public string ExciseReason { get; set; }
        public bool ExciseRebate { get; set; }
        public decimal ExcRate { get; set; }
        public string ExcUnits { get; set; }
        public double Factor { get; set; }
        public decimal GSIAmt { get; set; }
        public decimal GSIRate { get; set; }
        public string HWSerial { get; set; }
        public string HWSerial2 { get; set; }
        public bool IsNotExcise { get; set; }
        public string MainType { get; set; }
        public decimal MRPRate { get; set; }
        public decimal NCCDAmt { get; set; }
        public decimal NCCDRate { get; set; }
        public decimal oDuty1 { get; set; }
        public decimal oDuty2 { get; set; }
        public decimal oDuty3 { get; set; }
        public decimal oDutyAmt1 { get; set; }
        public decimal oDutyAmt2 { get; set; }
        public decimal oDutyAmt3 { get; set; }
        public string PeriodCode { get; set; }
        public string Prefix { get; set; }
        public decimal Qty { get; set; }
        public decimal Qty2 { get; set; }
        public decimal Rate { get; set; }
        public decimal ReasonType { get; set; }
        public decimal SEDAmt { get; set; }
        public decimal SEDRate { get; set; }
        public decimal SHECess { get; set; }
        public decimal SHECessAmt { get; set; }
        public string Sno { get; set; }
        public string Srl { get; set; }
        public string SubType { get; set; }
        public bool SuppInvoice { get; set; }
        public string Tariff { get; set; }
        public string TariffGrp { get; set; }
        public decimal TotADC { get; set; }
        public decimal TotADCAmt { get; set; }
        public decimal TotAssAmt { get; set; }
        public decimal TotBCD { get; set; }
        public decimal TotBCDAmt { get; set; }
        public decimal TotBEDAmt { get; set; }
        public decimal TotCess { get; set; }
        public decimal TotCessAmt { get; set; }
        public decimal TotExcAmt { get; set; }
        public decimal TotExcRate { get; set; }
        public decimal TotGSIAmt { get; set; }
        public decimal TotGSIRate { get; set; }
        public decimal TotNCCDAmt { get; set; }
        public decimal TotNCCDRate { get; set; }
        public decimal TotoDuty1 { get; set; }
        public decimal TotoDuty2 { get; set; }
        public decimal TotoDuty3 { get; set; }
        public decimal TotoDutyAmt1 { get; set; }
        public decimal TotoDutyAmt2 { get; set; }
        public decimal TotoDutyAmt3 { get; set; }
        public decimal TotSEDAmt { get; set; }
        public decimal TotSEDRate { get; set; }
        public decimal TotSHECess { get; set; }
        public decimal TotSHECessAmt { get; set; }
        public decimal TotTTAAmt { get; set; }
        public decimal TotTTARate { get; set; }
        public decimal TTAAmt { get; set; }
        public decimal TTARate { get; set; }
        public string Type { get; set; }
        public string Unit { get; set; }
        public string Unit2 { get; set; }
        public decimal TOUCHVALUE { get; set; }
        public string EnteredBy { get; set; }
        public System.DateTime LastUpdateDate { get; set; }
    
        public virtual Stock Stock { get; set; }
    }
}
