//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFATERPWebApplication.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockClass
    {
        public int RecordKey { get; set; }
        public string AccPeriod { get; set; }
        public decimal AddTax { get; set; }
        public string Allocation { get; set; }
        public string AuthIds { get; set; }
        public string Authorise { get; set; }
        public decimal BCD { get; set; }
        public decimal BCDAmt { get; set; }
        public string Branch { get; set; }
        public bool CancFlag { get; set; }
        public decimal Cess { get; set; }
        public string ClassValue { get; set; }
        public string Code { get; set; }
        public string cValues { get; set; }
        public decimal DispCol { get; set; }
        public decimal DispRow { get; set; }
        public System.DateTime DocDate { get; set; }
        public int Fld { get; set; }
        public string HWSerial { get; set; }
        public string HWSerial2 { get; set; }
        public string ItemCategory { get; set; }
        public string MainType { get; set; }
        public decimal MRP { get; set; }
        public bool NotInStock { get; set; }
        public decimal oDuty1 { get; set; }
        public decimal oDuty2 { get; set; }
        public decimal oDuty3 { get; set; }
        public decimal oDutyAmt1 { get; set; }
        public decimal oDutyAmt2 { get; set; }
        public decimal oDutyAmt3 { get; set; }
        public decimal Pending { get; set; }
        public decimal Pending2 { get; set; }
        public string PeriodCode { get; set; }
        public string Prefix { get; set; }
        public string ProcessCode { get; set; }
        public decimal Qty { get; set; }
        public decimal Rate { get; set; }
        public string RefNumber { get; set; }
        public string RevEntry { get; set; }
        public decimal SHECess { get; set; }
        public decimal SHECessAmt { get; set; }
        public string Sno { get; set; }
        public string Srl { get; set; }
        public string Store { get; set; }
        public string SubType { get; set; }
        public decimal SurCharge { get; set; }
        public decimal Taxable { get; set; }
        public decimal TaxAmt { get; set; }
        public string TaxCode { get; set; }
        public string Type { get; set; }
        public string xValue1 { get; set; }
        public string xValue2 { get; set; }
        public string xValue3 { get; set; }
        public decimal TOUCHVALUE { get; set; }
        public string EnteredBy { get; set; }
        public System.DateTime LastUpdateDate { get; set; }
    }
}
