//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFATERPWebApplication.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockMore
    {
        public int RecordKey { get; set; }
        public decimal AcceptedQty { get; set; }
        public string AccPeriod { get; set; }
        public short AltAddress { get; set; }
        public string AuthIds { get; set; }
        public string Authorise { get; set; }
        public decimal BatchQty { get; set; }
        public string Branch { get; set; }
        public string Broker { get; set; }
        public decimal Brokerage { get; set; }
        public decimal BrokerAmt { get; set; }
        public decimal BrokerOn { get; set; }
        public string CatNo { get; set; }
        public string Code { get; set; }
        public int CrPeriod { get; set; }
        public string Division { get; set; }
        public System.DateTime DocDate { get; set; }
        public System.DateTime ExpDate { get; set; }
        public double Factor { get; set; }
        public decimal IDisc { get; set; }
        public decimal IDiscAmt { get; set; }
        public decimal InvoiceQty { get; set; }
        public decimal IRate { get; set; }
        public string ItemCategory { get; set; }
        public decimal LabourAmt { get; set; }
        public decimal MachineAmt { get; set; }
        public decimal MachineChgs { get; set; }
        public string MachineCode { get; set; }
        public string MainType { get; set; }
        public System.DateTime MfgDate { get; set; }
        public decimal MRP { get; set; }
        public bool NoExpiry { get; set; }
        public int NoHrs { get; set; }
        public decimal OtherAmt { get; set; }
        public string Party { get; set; }
        public decimal PDisc { get; set; }
        public decimal PDiscAmt { get; set; }
        public string PeriodCode { get; set; }
        public decimal PRate { get; set; }
        public decimal PreDisc { get; set; }
        public decimal PreDiscAmt { get; set; }
        public string Prefix { get; set; }
        public decimal PreRate { get; set; }
        public string ProjectCode { get; set; }
        public string ProjectStage { get; set; }
        public string ProjectUnit { get; set; }
        public decimal Qty { get; set; }
        public decimal Qty2 { get; set; }
        public string QtyEqsn { get; set; }
        public decimal RatePerHr { get; set; }
        public bool RateVerify { get; set; }
        public decimal ReasonType { get; set; }
        public decimal RejectedQty { get; set; }
        public string RejStore { get; set; }
        public decimal SalemanAmt { get; set; }
        public decimal SalemanOn { get; set; }
        public decimal SalemanPer { get; set; }
        public string SalesMan { get; set; }
        public short Shift { get; set; }
        public string Sno { get; set; }
        public string Srl { get; set; }
        public string SubType { get; set; }
        public string Type { get; set; }
        public string Unit2 { get; set; }
        public string WasteFlag { get; set; }
        public decimal TOUCHVALUE { get; set; }
        public string EnteredBy { get; set; }
        public System.DateTime LastUpdateDate { get; set; }
        public string HWSERIAL { get; set; }
        public string HWSERIAL2 { get; set; }
    
        public virtual Stock Stock { get; set; }
    }
}
