//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFATERPWebApplication.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockSerial
    {
        public int RecordKey { get; set; }
        public string AccPeriod { get; set; }
        public string AuthIds { get; set; }
        public string Authorise { get; set; }
        public System.DateTime BillDate { get; set; }
        public string BillNumber { get; set; }
        public string Branch { get; set; }
        public string Code { get; set; }
        public System.DateTime DocDate { get; set; }
        public decimal GrossWt { get; set; }
        public string HWSerial { get; set; }
        public string HWSerial2 { get; set; }
        public string ItemCategory { get; set; }
        public string MainType { get; set; }
        public decimal NettWt { get; set; }
        public decimal NewRate { get; set; }
        public bool NotInStock { get; set; }
        public string PartyCode { get; set; }
        public string PeriodCode { get; set; }
        public string Prefix { get; set; }
        public decimal Qty { get; set; }
        public decimal Rate { get; set; }
        public string Reference { get; set; }
        public string RevEntry { get; set; }
        public string SerialNumber { get; set; }
        public string Sno { get; set; }
        public decimal sQty { get; set; }
        public string Srl { get; set; }
        public string Store { get; set; }
        public string SubType { get; set; }
        public bool TagPrepared { get; set; }
        public string Type { get; set; }
        public decimal TOUCHVALUE { get; set; }
        public string EnteredBy { get; set; }
        public System.DateTime LastUpdateDate { get; set; }
    }
}
