//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFATERPWebApplication.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockQC
    {
        public int RecordKey { get; set; }
        public string AccPeriod { get; set; }
        public decimal Amt { get; set; }
        public string AuthIds { get; set; }
        public string Authorise { get; set; }
        public string Branch { get; set; }
        public string Code { get; set; }
        public System.DateTime DocDate { get; set; }
        public double Factor { get; set; }
        public string GINNumber { get; set; }
        public string HWSerial { get; set; }
        public string HWSerial2 { get; set; }
        public string ItemCategory { get; set; }
        public string MainType { get; set; }
        public string Party { get; set; }
        public string PeriodCode { get; set; }
        public string Prefix { get; set; }
        public string ProcessCode { get; set; }
        public string QCCode { get; set; }
        public bool QCDone { get; set; }
        public string QCNarr { get; set; }
        public System.DateTime QCTimeIn { get; set; }
        public System.DateTime QCTimeOut { get; set; }
        public string QCType { get; set; }
        public decimal Qty { get; set; }
        public decimal Qty2 { get; set; }
        public int QtySno { get; set; }
        public decimal Rate { get; set; }
        public string Reason { get; set; }
        public decimal RejectQty { get; set; }
        public string RejStore { get; set; }
        public bool SelfCertified { get; set; }
        public string Sno { get; set; }
        public string Srl { get; set; }
        public int Stage { get; set; }
        public string Store { get; set; }
        public string SubType { get; set; }
        public string Type { get; set; }
        public string Unit { get; set; }
        public string Unit2 { get; set; }
        public string WONumber { get; set; }
        public decimal TOUCHVALUE { get; set; }
        public string EnteredBy { get; set; }
        public System.DateTime LastUpdateDate { get; set; }
    }
}
