//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFATERPWebApplication.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockReserve
    {
        public int RecordKey { get; set; }
        public string AccPeriod { get; set; }
        public string Branch { get; set; }
        public bool CancFlag { get; set; }
        public string Code { get; set; }
        public System.DateTime DocDate { get; set; }
        public decimal Pending { get; set; }
        public string PeriodCode { get; set; }
        public string Prefix { get; set; }
        public string RefDocument { get; set; }
        public decimal ReservedQty { get; set; }
        public string Sno { get; set; }
        public string Srl { get; set; }
        public string Store { get; set; }
        public decimal TouchValue { get; set; }
        public string Type { get; set; }
        public string EnteredBy { get; set; }
        public System.DateTime LastUpdateDate { get; set; }
        public string AUTHORISE { get; set; }
        public string AUTHIDS { get; set; }
        public string HWSERIAL { get; set; }
        public string HWSERIAL2 { get; set; }
        public string ParentDoc { get; set; }
    }
}
