//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFATERPWebApplication.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockBatch
    {
        public int RecordKey { get; set; }
        public string AccPeriod { get; set; }
        public string AuthIds { get; set; }
        public string Authorise { get; set; }
        public string Batch { get; set; }
        public string BatchParent { get; set; }
        public string Branch { get; set; }
        public string Code { get; set; }
        public System.DateTime DocDate { get; set; }
        public System.DateTime ExpDate { get; set; }
        public double Factor { get; set; }
        public string HWSerial { get; set; }
        public string HWSerial2 { get; set; }
        public string ItemCategory { get; set; }
        public string MainType { get; set; }
        public System.DateTime MfgDate { get; set; }
        public decimal MRP { get; set; }
        public string Narr { get; set; }
        public decimal NewRate { get; set; }
        public bool NoExpiry { get; set; }
        public bool NotInStock { get; set; }
        public string Party { get; set; }
        public string PeriodCode { get; set; }
        public string Prefix { get; set; }
        public decimal Qty { get; set; }
        public decimal Qty2 { get; set; }
        public decimal Rate { get; set; }
        public string SerialNumber { get; set; }
        public string Sno { get; set; }
        public string Srl { get; set; }
        public string Store { get; set; }
        public string SubType { get; set; }
        public string Type { get; set; }
        public decimal TOUCHVALUE { get; set; }
        public string EnteredBy { get; set; }
        public System.DateTime LastUpdateDate { get; set; }
    }
}
