//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFATERPWebApplication.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockO
    {
        public int RecordKey { get; set; }
        public decimal AcceptedQty { get; set; }
        public string AccPeriod { get; set; }
        public decimal ADC { get; set; }
        public decimal AddTax { get; set; }
        public string aMaintype { get; set; }
        public decimal Amt { get; set; }
        public string aPrefix { get; set; }
        public string aSerial { get; set; }
        public string aSno { get; set; }
        public string aSubType { get; set; }
        public string aType { get; set; }
        public bool Audited { get; set; }
        public string AuthIds { get; set; }
        public string Authorise { get; set; }
        public string Batch { get; set; }
        public decimal BCD { get; set; }
        public decimal BCDAmt { get; set; }
        public System.DateTime BillDate { get; set; }
        public string BillNumber { get; set; }
        public string Branch { get; set; }
        public string Broker { get; set; }
        public decimal Brokerage { get; set; }
        public decimal BrokerAmt { get; set; }
        public decimal BrokerOn { get; set; }
        public decimal Cess { get; set; }
        public System.DateTime ChlnDate { get; set; }
        public string ChlnNumber { get; set; }
        public string Code { get; set; }
        public int CrPeriod { get; set; }
        public string CurrName { get; set; }
        public decimal CurrRate { get; set; }
        public decimal Disc { get; set; }
        public decimal DiscAmt { get; set; }
        public decimal Discount { get; set; }
        public System.DateTime DocDate { get; set; }
        public decimal ExciseAs { get; set; }
        public System.DateTime ExpDate { get; set; }
        public double Factor { get; set; }
        public bool FreeQty { get; set; }
        public string HWSerial { get; set; }
        public string HWSerial2 { get; set; }
        public decimal InvoiceQty { get; set; }
        public string ItemCategory { get; set; }
        public string MainType { get; set; }
        public System.DateTime MfgDate { get; set; }
        public decimal MRP { get; set; }
        public string Narr { get; set; }
        public decimal NewRate { get; set; }
        public decimal NewRateEntry { get; set; }
        public decimal NewRateLink { get; set; }
        public bool NoExpiry { get; set; }
        public bool NotInStock { get; set; }
        public decimal oDuty1 { get; set; }
        public decimal oDuty2 { get; set; }
        public decimal oDuty3 { get; set; }
        public decimal oDutyAmt1 { get; set; }
        public decimal oDutyAmt2 { get; set; }
        public decimal oDutyAmt3 { get; set; }
        public System.DateTime OrdDate { get; set; }
        public string OrdNumber { get; set; }
        public decimal OriginalQty { get; set; }
        public string Party { get; set; }
        public decimal Pending { get; set; }
        public decimal Pending2 { get; set; }
        public decimal PendingWt { get; set; }
        public string PeriodCode { get; set; }
        public string PerUnit { get; set; }
        public string Prefix { get; set; }
        public short ProcessStage { get; set; }
        public decimal Qty { get; set; }
        public decimal Qty2 { get; set; }
        public string QtyEqsn { get; set; }
        public decimal Rate { get; set; }
        public decimal RateOn { get; set; }
        public decimal RatePer { get; set; }
        public string Reason { get; set; }
        public decimal RejectedQty { get; set; }
        public string RejStore { get; set; }
        public decimal RG23DEntryNo { get; set; }
        public decimal RG23DPageNo { get; set; }
        public decimal SalemanAmt { get; set; }
        public decimal SalemanOn { get; set; }
        public decimal SalemanPer { get; set; }
        public string SalesMan { get; set; }
        public decimal SHECess { get; set; }
        public decimal SHECessAmt { get; set; }
        public string Sno { get; set; }
        public string Srl { get; set; }
        public int Stage { get; set; }
        public decimal STAmt { get; set; }
        public decimal Staxable { get; set; }
        public decimal STCess { get; set; }
        public string STCode { get; set; }
        public short Stocktran { get; set; }
        public string Store { get; set; }
        public decimal STSheCess { get; set; }
        public string SubType { get; set; }
        public decimal SurCharge { get; set; }
        public string TariffGrp { get; set; }
        public decimal Taxable { get; set; }
        public decimal TaxAmt { get; set; }
        public string TaxCode { get; set; }
        public string Type { get; set; }
        public string Unit { get; set; }
        public string Unit2 { get; set; }
        public string WasteFlag { get; set; }
        public decimal Weightage { get; set; }
        public string WONumber { get; set; }
        public string WorkOrder { get; set; }
        public decimal Wt { get; set; }
        public decimal TOUCHVALUE { get; set; }
        public string EnteredBy { get; set; }
        public System.DateTime LastUpdateDate { get; set; }
    
        public virtual Stock Stock { get; set; }
    }
}
