//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFATERPWebApplication.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockAdj
    {
        public int RecordKey { get; set; }
        public string AccPeriod { get; set; }
        public string aMainType { get; set; }
        public decimal Amt { get; set; }
        public string APrefix { get; set; }
        public string ASerial { get; set; }
        public string ASno { get; set; }
        public string ASubType { get; set; }
        public string AType { get; set; }
        public string AuthIds { get; set; }
        public string Authorise { get; set; }
        public string Batch { get; set; }
        public System.DateTime BillDt { get; set; }
        public string BillNo { get; set; }
        public string Branch { get; set; }
        public string ChlnNumber { get; set; }
        public string Code { get; set; }
        public string CurrName { get; set; }
        public decimal CurrRate { get; set; }
        public decimal Disc { get; set; }
        public decimal DiscAmt { get; set; }
        public System.DateTime DocDate { get; set; }
        public string HWSerial { get; set; }
        public string HWSerial2 { get; set; }
        public string ItemCategory { get; set; }
        public string MainType { get; set; }
        public string Narr { get; set; }
        public bool NotInStock { get; set; }
        public string OrdNumber { get; set; }
        public string Party { get; set; }
        public decimal PendQty { get; set; }
        public string PeriodCode { get; set; }
        public string PerUnit { get; set; }
        public string Prefix { get; set; }
        public decimal Qty { get; set; }
        public decimal Rate { get; set; }
        public decimal RatePer { get; set; }
        public string Sno { get; set; }
        public string Srl { get; set; }
        public string Store { get; set; }
        public string SubType { get; set; }
        public string Type { get; set; }
        public string Unit { get; set; }
        public decimal TOUCHVALUE { get; set; }
        public string EnteredBy { get; set; }
        public System.DateTime LastUpdateDate { get; set; }
    }
}
