//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFATERPWebApplication.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Store
    {
        public Store()
        {
            this.Stocks = new HashSet<Stock>();
        }
    
        public int RecordKey { get; set; }
        public string Adrl1 { get; set; }
        public string Adrl2 { get; set; }
        public string Adrl3 { get; set; }
        public bool AllowCrCard { get; set; }
        public bool AllowNeg { get; set; }
        public bool AllowRateChange { get; set; }
        public string AppBranch { get; set; }
        public string AppGroup { get; set; }
        public string Area { get; set; }
        public string AuthIds { get; set; }
        public string Authorise { get; set; }
        public string BillFormat { get; set; }
        public string BillPrinter { get; set; }
        public bool CardMode { get; set; }
        public string City { get; set; }
        public string Code { get; set; }
        public string CostCentre { get; set; }
        public string Country { get; set; }
        public decimal CrewSize { get; set; }
        public string DefaultServiceType { get; set; }
        public bool DirectBill { get; set; }
        public bool DirectSettlement { get; set; }
        public decimal Efficiency { get; set; }
        public string Flag { get; set; }
        public string Footer { get; set; }
        public bool ForceCaptain { get; set; }
        public bool ForceServer { get; set; }
        public string Grp { get; set; }
        public decimal HappyFriFrom { get; set; }
        public decimal HappyFriTo { get; set; }
        public string HappyMenuCode { get; set; }
        public decimal HappyMonFrom { get; set; }
        public decimal HappyMonTo { get; set; }
        public decimal HappySatFrom { get; set; }
        public decimal HappySatTo { get; set; }
        public decimal HappySunFrom { get; set; }
        public decimal HappySunTo { get; set; }
        public decimal HappyThuFrom { get; set; }
        public decimal HappyThuTo { get; set; }
        public decimal HappyTueFrom { get; set; }
        public decimal HappyTueTo { get; set; }
        public decimal HappyWedFrom { get; set; }
        public decimal HappyWedTo { get; set; }
        public string Header { get; set; }
        public bool Hide { get; set; }
        public string HWSerial { get; set; }
        public string HWSerial2 { get; set; }
        public string Incharge { get; set; }
        public bool IsLast { get; set; }
        public string KOTFormat { get; set; }
        public string KOTFormatCancel { get; set; }
        public string KOTPrinter { get; set; }
        public bool LocalPrinter { get; set; }
        public bool Locked { get; set; }
        public decimal Machines { get; set; }
        public string MenuCode { get; set; }
        public decimal MoveHour { get; set; }
        public string Name { get; set; }
        public bool OverReserve { get; set; }
        public string Party { get; set; }
        public string Pin { get; set; }
        public string ProcessCode { get; set; }
        public string ProjectCode { get; set; }
        public decimal QueueHour { get; set; }
        public bool QuickService { get; set; }
        public decimal ReplHour { get; set; }
        public decimal Shift1 { get; set; }
        public decimal Shift1B1 { get; set; }
        public decimal Shift1End { get; set; }
        public decimal Shift2 { get; set; }
        public decimal Shift2B1 { get; set; }
        public decimal Shift2End { get; set; }
        public decimal Shift3 { get; set; }
        public decimal Shift3B1 { get; set; }
        public decimal Shift3End { get; set; }
        public bool ShiftApp2 { get; set; }
        public bool ShiftApp3 { get; set; }
        public string State { get; set; }
        public bool StockReserve { get; set; }
        public bool StopBill { get; set; }
        public bool StopKOT { get; set; }
        public bool StopSettlement { get; set; }
        public short StoreType { get; set; }
        public bool TaxApplicable { get; set; }
        public string Telephone { get; set; }
        public string TypeBill { get; set; }
        public string TypeKOT { get; set; }
        public string TypeSettle { get; set; }
        public string Users { get; set; }
        public decimal Utilisation { get; set; }
        public decimal WorkHours { get; set; }
        public decimal TOUCHVALUE { get; set; }
        public string EnteredBy { get; set; }
        public System.DateTime LastUpdateDate { get; set; }
    
        public virtual ICollection<Stock> Stocks { get; set; }
    }
}
