//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFATERPWebApplication.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubLedger
    {
        public SubLedger()
        {
            this.Ledgers = new HashSet<Ledger>();
        }
    
        public int RecordKey { get; set; }
        public string Adrl1 { get; set; }
        public string Adrl2 { get; set; }
        public string Adrl3 { get; set; }
        public string Area { get; set; }
        public string City { get; set; }
        public string Code { get; set; }
        public string Country { get; set; }
        public string Email { get; set; }
        public string Flag { get; set; }
        public string Grp { get; set; }
        public bool IsLast { get; set; }
        public bool Locked { get; set; }
        public string Mobile { get; set; }
        public string Name { get; set; }
        public string Person { get; set; }
        public string Pin { get; set; }
        public string State { get; set; }
        public string Telephone { get; set; }
        public decimal TOUCHVALUE { get; set; }
        public string EnteredBy { get; set; }
        public System.DateTime LastUpdateDate { get; set; }
        public string AUTHORISE { get; set; }
        public string AUTHIDS { get; set; }
        public string HWSERIAL { get; set; }
        public string HWSERIAL2 { get; set; }
    
        public virtual ICollection<Ledger> Ledgers { get; set; }
    }
}
