//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFATERPWebApplication.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class SuchanProject
    {
        public string ProjectCode { get; set; }
        public string Club { get; set; }
        public string ISOCode { get; set; }
        public string ProjectName { get; set; }
        public string Sponsor { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string ProjectManager { get; set; }
        public string OptionCentric { get; set; }
        public string TestedBy { get; set; }
        public Nullable<System.DateTime> TestCompletedDate { get; set; }
        public Nullable<System.DateTime> AlphaDate { get; set; }
        public Nullable<System.DateTime> DlyAlphaDate { get; set; }
        public Nullable<System.DateTime> Beta1Date { get; set; }
        public Nullable<System.DateTime> DlyBeta1Date { get; set; }
        public Nullable<System.DateTime> Beta2Date { get; set; }
        public Nullable<System.DateTime> DlyBeta2Date { get; set; }
        public Nullable<System.DateTime> Beta3Date { get; set; }
        public Nullable<System.DateTime> DlyBeta3Date { get; set; }
        public Nullable<System.DateTime> FinalDlyDate { get; set; }
        public Nullable<System.DateTime> DlyFinalDlyDate { get; set; }
        public Nullable<System.DateTime> ProjectCloseDate { get; set; }
        public Nullable<System.DateTime> TrainingDate { get; set; }
        public Nullable<System.DateTime> DocumentDate { get; set; }
        public decimal TOUCHVALUE { get; set; }
        public int RecordKey { get; set; }
        public string EnteredBy { get; set; }
        public System.DateTime LastUpdateDate { get; set; }
        public string AUTHORISE { get; set; }
        public string AUTHIDS { get; set; }
        public string HWSERIAL { get; set; }
        public string HWSERIAL2 { get; set; }
    }
}
