//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFATERPWebApplication.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class TfatForm
    {
        public int RecordKey { get; set; }
        public string AuthIds { get; set; }
        public string Authorise { get; set; }
        public short AutoIncr { get; set; }
        public bool AutoSize { get; set; }
        public string BackColor { get; set; }
        public bool BarCoded { get; set; }
        public bool Border { get; set; }
        public string Caption { get; set; }
        public bool Comma { get; set; }
        public string Cond { get; set; }
        public string ControlType { get; set; }
        public short CPI { get; set; }
        public short CPIStyle { get; set; }
        public short DecS { get; set; }
        public string Equation { get; set; }
        public bool Fixed { get; set; }
        public string FldType { get; set; }
        public bool FontBold { get; set; }
        public bool FontItalics { get; set; }
        public string FontName { get; set; }
        public short FontSize { get; set; }
        public bool FontStrike { get; set; }
        public bool FontUnderLine { get; set; }
        public string ForeColor { get; set; }
        public string Format { get; set; }
        public string FromRs { get; set; }
        public bool GroupHeader { get; set; }
        public int Height { get; set; }
        public string HWSerial { get; set; }
        public string HWSerial2 { get; set; }
        public short Justify { get; set; }
        public bool Locked { get; set; }
        public short OnPage { get; set; }
        public short PageJustify { get; set; }
        public bool PrintInHeader { get; set; }
        public short Sections { get; set; }
        public bool SpaceSaver { get; set; }
        public int Width { get; set; }
        public int WordWrapGap { get; set; }
        public bool WordWrapS { get; set; }
        public int X1 { get; set; }
        public int X2 { get; set; }
        public int Y1 { get; set; }
        public int Y2 { get; set; }
        public decimal TOUCHVALUE { get; set; }
        public string EnteredBy { get; set; }
        public System.DateTime LastUpdateDate { get; set; }
    }
}
