//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFATERPWebApplication.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class TfatComp
    {
        public TfatComp()
        {
            this.TFatBranches = new HashSet<TFatBranch>();
        }
    
        public int RecordKey { get; set; }
        public string Adrl1 { get; set; }
        public string Adrl2 { get; set; }
        public string Adrl3 { get; set; }
        public string Adrl4 { get; set; }
        public string AssessOffice { get; set; }
        public decimal AuthCap { get; set; }
        public string AuthIds { get; set; }
        public string AuthNo { get; set; }
        public string Authorise { get; set; }
        public string Business { get; set; }
        public string City { get; set; }
        public string Code { get; set; }
        public string CompanyLogo { get; set; }
        public short CompanyType { get; set; }
        public string CompInfo { get; set; }
        public string Const { get; set; }
        public string Country { get; set; }
        public string cstno { get; set; }
        public string DDOCode { get; set; }
        public string DDOReg { get; set; }
        public string DeductorType { get; set; }
        public string EMail { get; set; }
        public string fax { get; set; }
        public string HWSerial { get; set; }
        public string HWSerial2 { get; set; }
        public string LastBranch { get; set; }
        public string LastPeriod { get; set; }
        public string Licence1 { get; set; }
        public string Licence2 { get; set; }
        public string lstno { get; set; }
        public int Ministry { get; set; }
        public string Name { get; set; }
        public string Nature { get; set; }
        public string PAN { get; set; }
        public string PAOCode { get; set; }
        public string PAOReg { get; set; }
        public bool PFFix { get; set; }
        public string PFupLimit { get; set; }
        public string Pin { get; set; }
        public string ServiceTaxNo { get; set; }
        public string SMSURL { get; set; }
        public string State { get; set; }
        public string STDCode { get; set; }
        public string Taluka { get; set; }
        public string TDSCir { get; set; }
        public string TDSReg { get; set; }
        public string Tel1 { get; set; }
        public string Tel2 { get; set; }
        public string Tel3 { get; set; }
        public string Tel4 { get; set; }
        public string TINNo { get; set; }
        public decimal TouchValue { get; set; }
        public string USERPass { get; set; }
        public string Users { get; set; }
        public string VATReg { get; set; }
        public string www { get; set; }
        public string xState { get; set; }
        public string EnteredBy { get; set; }
        public System.DateTime LastUpdateDate { get; set; }
    
        public virtual ICollection<TFatBranch> TFatBranches { get; set; }
    }
}
