//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFATERPWebApplication.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class TfatDesignForm
    {
        public int FormRecordKey { get; set; }
        public int HeaderRecordKey { get; set; }
        public string Fle { get; set; }
        public string Fld { get; set; }
        public Nullable<byte> FldSize { get; set; }
        public string fType { get; set; }
        public string ControlType { get; set; }
        public Nullable<bool> NotZero { get; set; }
        public Nullable<byte> Decs { get; set; }
        public Nullable<short> DisplayOrder { get; set; }
        public Nullable<bool> Enabled { get; set; }
        public Nullable<bool> Visible { get; set; }
        public Nullable<bool> Locked { get; set; }
        public Nullable<bool> CarryForward { get; set; }
        public string LabelCaption { get; set; }
        public string NewGroup { get; set; }
        public Nullable<bool> LabelAutoSize { get; set; }
        public string TabName { get; set; }
        public Nullable<bool> IsButton { get; set; }
        public string LetterCase { get; set; }
        public Nullable<bool> AllowBlank { get; set; }
        public string eDepend { get; set; }
        public string vDepend { get; set; }
        public string FldValues { get; set; }
        public string DefaultValue { get; set; }
        public string DontAllow { get; set; }
        public string Meaning { get; set; }
        public string FontName { get; set; }
        public Nullable<byte> FontSize { get; set; }
        public Nullable<bool> FontItalics { get; set; }
        public Nullable<bool> FontBold { get; set; }
        public Nullable<bool> FontUnderLine { get; set; }
        public Nullable<bool> FontStrikethru { get; set; }
        public Nullable<short> Sno { get; set; }
        public Nullable<short> ColWidth { get; set; }
        public string Triggers { get; set; }
        public Nullable<short> Columns { get; set; }
        public string GridFldValueUrl { get; set; }
        public Nullable<byte> Section { get; set; }
        public decimal TOUCHVALUE { get; set; }
        public int RecordKey { get; set; }
        public string EnteredBy { get; set; }
        public System.DateTime LastUpdateDate { get; set; }
        public string AUTHORISE { get; set; }
        public string AUTHIDS { get; set; }
        public string HWSERIAL { get; set; }
        public string HWSERIAL2 { get; set; }
    
        public virtual TfatDesignHeader TfatDesignHeader { get; set; }
    }
}
