//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFATERPWebApplication.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class TfatPerd
    {
        public int RecordKey { get; set; }
        public string AuthIds { get; set; }
        public string Authorise { get; set; }
        public string Code { get; set; }
        public string DatabaseName { get; set; }
        public bool DbOffLine { get; set; }
        public string HWSerial { get; set; }
        public string HWSerial2 { get; set; }
        public System.DateTime LastDate { get; set; }
        public bool Locked { get; set; }
        public bool MasUpdate { get; set; }
        public bool NewUpdate { get; set; }
        public string PerdCode { get; set; }
        public string PeriodCode { get; set; }
        public System.DateTime StartDate { get; set; }
        public decimal TouchValue { get; set; }
        public string EnteredBy { get; set; }
        public System.DateTime LastUpdateDate { get; set; }
    }
}
