//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFATERPWebApplication.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class TfatPass
    {
        public TfatPass()
        {
            this.Ledgers = new HashSet<Ledger>();
            this.Masters = new HashSet<Master>();
            this.Masters1 = new HashSet<Master>();
            this.Sales = new HashSet<Sale>();
            this.Stocks = new HashSet<Stock>();
        }
    
        public int RecordKey { get; set; }
        public string AccountRights { get; set; }
        public short ActiveAssist { get; set; }
        public string AllowAreas { get; set; }
        public string AllowCategory { get; set; }
        public bool Animate { get; set; }
        public string AppBranch { get; set; }
        public string Assistant { get; set; }
        public bool AuditTrail { get; set; }
        public string AuthIds { get; set; }
        public string Authorise { get; set; }
        public int AuthRec { get; set; }
        public bool BoldFont { get; set; }
        public bool ChangeForm { get; set; }
        public short CheckMark { get; set; }
        public string ClickSequence { get; set; }
        public short ColScheme { get; set; }
        public bool Control3D { get; set; }
        public string CorpID { get; set; }
        public bool DailyPassword { get; set; }
        public string Dept { get; set; }
        public bool DeskTop { get; set; }
        public bool DontChangePassword { get; set; }
        public string EmailClient { get; set; }
        public string EmailID { get; set; }
        public bool EnterKey { get; set; }
        public System.DateTime Expiry { get; set; }
        public string Flag { get; set; }
        public bool FontBoldBtn { get; set; }
        public bool FontBoldGrdC { get; set; }
        public bool FontBoldGrdH { get; set; }
        public bool FontBoldLbl { get; set; }
        public bool FontBoldTxt { get; set; }
        public string FontName { get; set; }
        public string FontNameBtn { get; set; }
        public string FontNameGrdC { get; set; }
        public string FontNameGrdH { get; set; }
        public string FontNameLbl { get; set; }
        public string FontNameTxt { get; set; }
        public short FontSize { get; set; }
        public short FontSizeBtn { get; set; }
        public short FontSizeGrdC { get; set; }
        public short FontSizeGrdH { get; set; }
        public short FontSizeLbl { get; set; }
        public short FontSizeTxt { get; set; }
        public bool ForceResize { get; set; }
        public bool FormCaption { get; set; }
        public bool Fri { get; set; }
        public bool HelpOnStart { get; set; }
        public bool Hide { get; set; }
        public bool HomeWorkflow { get; set; }
        public string HWSerial { get; set; }
        public string HWSerial2 { get; set; }
        public string IDs { get; set; }
        public bool InBox { get; set; }
        public bool InboxDelete { get; set; }
        public bool IsHead { get; set; }
        public string LastBranch { get; set; }
        public string LastBranchUsed { get; set; }
        public string LastComp { get; set; }
        public string LastCompany { get; set; }
        public System.DateTime LastLastDt { get; set; }
        public System.DateTime LastLicReminder { get; set; }
        public System.DateTime LastLogin { get; set; }
        public System.DateTime LastStartDt { get; set; }
        public bool LastUser { get; set; }
        public bool Learning { get; set; }
        public bool LicReminder { get; set; }
        public bool Locked { get; set; }
        public string LogIns { get; set; }
        public bool MainCentre { get; set; }
        public int MaxTrx { get; set; }
        public string Mobile { get; set; }
        public bool Mon { get; set; }
        public int MsgDays { get; set; }
        public bool MsgPopup { get; set; }
        public string Name { get; set; }
        public bool NoRightClick { get; set; }
        public string OptionAlign { get; set; }
        public short OptionTab { get; set; }
        public string PassRead { get; set; }
        public string PassWords { get; set; }
        public string Photograph { get; set; }
        public string POPServer { get; set; }
        public string PrGroup { get; set; }
        public bool PrintControl { get; set; }
        public string ProductRights { get; set; }
        public bool RateHistory { get; set; }
        public bool RecMsg { get; set; }
        public bool RecSMS { get; set; }
        public bool RestrictWS { get; set; }
        public bool Sat { get; set; }
        public string Signature { get; set; }
        public string SMTPPassword { get; set; }
        public int SMTPPort { get; set; }
        public bool SMTPRoute { get; set; }
        public string SMTPServer { get; set; }
        public string SMTPUser { get; set; }
        public bool SoundEvent { get; set; }
        public bool StartRem { get; set; }
        public string StartUpForm { get; set; }
        public bool StartUpMemo { get; set; }
        public bool StatusBar { get; set; }
        public bool Sun { get; set; }
        public bool Thu { get; set; }
        public short TipOnStart { get; set; }
        public short ToolBar { get; set; }
        public short ToolBarDisplay { get; set; }
        public decimal TouchValue { get; set; }
        public bool Tue { get; set; }
        public string UserRole { get; set; }
        public string WallPaper { get; set; }
        public bool Wed { get; set; }
        public string WorkStation { get; set; }
        public string WSLogin { get; set; }
        public string EnteredBy { get; set; }
        public System.DateTime LastUpdateDate { get; set; }
    
        public virtual ICollection<Ledger> Ledgers { get; set; }
        public virtual ICollection<Master> Masters { get; set; }
        public virtual ICollection<Master> Masters1 { get; set; }
        public virtual ICollection<Sale> Sales { get; set; }
        public virtual ICollection<Stock> Stocks { get; set; }
    }
}
