//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFATERPWebApplication.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class TfatDesignHeader
    {
        public TfatDesignHeader()
        {
            this.TfatDesignForms = new HashSet<TfatDesignForm>();
        }
    
        public string ProjectCode { get; set; }
        public int HeaderRecordKey { get; set; }
        public string OptionName { get; set; }
        public string LikeOptionCode { get; set; }
        public string DatabaseName { get; set; }
        public string TableName { get; set; }
        public string IDKey { get; set; }
        public string TableRelation { get; set; }
        public bool AutoCode { get; set; }
        public string KeyStart { get; set; }
        public Nullable<byte> KeyLength { get; set; }
        public bool EmbedZero { get; set; }
        public bool InsertMissing { get; set; }
        public string SerialCond { get; set; }
        public string Filter { get; set; }
        public string Status { get; set; }
        public bool IsPrefix { get; set; }
        public bool UpdateOnly { get; set; }
        public bool xAdd { get; set; }
        public bool xEdit { get; set; }
        public bool xDelete { get; set; }
        public bool xPrint { get; set; }
        public bool EditInGrid { get; set; }
        public string SPDelete { get; set; }
        public string Tabs { get; set; }
        public string HelpFlds { get; set; }
        public string OptionInfo { get; set; }
        public string PreEdit { get; set; }
        public string PreSave { get; set; }
        public string PostSave { get; set; }
        public string FunctionButton { get; set; }
        public Nullable<short> Width { get; set; }
        public Nullable<short> Height { get; set; }
        public Nullable<short> RowHeight { get; set; }
        public bool AllowDuplicate { get; set; }
        public bool BarCodePrint { get; set; }
        public bool PrintOnSave { get; set; }
        public bool ForceGrid { get; set; }
        public string TreeParentFld { get; set; }
        public Nullable<short> MaxGrid { get; set; }
        public string AddSubmitUrl { get; set; }
        public string AddUrl { get; set; }
        public string AddName { get; set; }
        public string EditSubmitUrl { get; set; }
        public string EditUrl { get; set; }
        public string EditName { get; set; }
        public string DeleteSubmitUrl { get; set; }
        public string DeleteName { get; set; }
        public string DeleteUrl { get; set; }
        public decimal TOUCHVALUE { get; set; }
        public int RecordKey { get; set; }
        public string EnteredBy { get; set; }
        public System.DateTime LastUpdateDate { get; set; }
        public string AUTHORISE { get; set; }
        public string AUTHIDS { get; set; }
        public string HWSERIAL { get; set; }
        public string HWSERIAL2 { get; set; }
        public string OptionCode { get; set; }
    
        public virtual ICollection<TfatDesignForm> TfatDesignForms { get; set; }
    }
}
