//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFATERPWebApplication.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class TfatMenu
    {
        public string ProjectCode { get; set; }
        public string Descr { get; set; }
        public Nullable<short> Display { get; set; }
        public string MenuID { get; set; }
        public string MenuParent { get; set; }
        public string FormName { get; set; }
        public Nullable<short> Depth { get; set; }
        public bool IsReport { get; set; }
        public bool IsLast { get; set; }
        public string OptionType { get; set; }
        public string OptionMode { get; set; }
        public string HotKey { get; set; }
        public string MenuUrl { get; set; }
        public decimal TOUCHVALUE { get; set; }
        public int RecordKey { get; set; }
        public string EnteredBy { get; set; }
        public System.DateTime LastUpdateDate { get; set; }
        public string AUTHORISE { get; set; }
        public string AUTHIDS { get; set; }
        public string HWSERIAL { get; set; }
        public string HWSERIAL2 { get; set; }
    }
}
