//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFATERPWebApplication.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class TfatState
    {
        public TfatState()
        {
            this.TfatCities = new HashSet<TfatCity>();
            this.Addresses = new HashSet<Address>();
            this.SalesMen = new HashSet<SalesMan>();
            this.ProjectDetails = new HashSet<ProjectDetail>();
        }
    
        public int RecordKey { get; set; }
        public string Name { get; set; }
        public int Country { get; set; }
        public int Code { get; set; }
        public string Authorise { get; set; }
        public string AuthIds { get; set; }
        public decimal Touchvalue { get; set; }
        public string HWSerial { get; set; }
        public string HWSERIAL2 { get; set; }
        public string EnteredBy { get; set; }
        public System.DateTime LastUpdateDate { get; set; }
    
        public virtual ICollection<TfatCity> TfatCities { get; set; }
        public virtual TfatCountry TfatCountry { get; set; }
        public virtual ICollection<Address> Addresses { get; set; }
        public virtual ICollection<SalesMan> SalesMen { get; set; }
        public virtual ICollection<ProjectDetail> ProjectDetails { get; set; }
    }
}
