//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFATERPWebApplication.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class TfatSearch
    {
        public int RecordKey { get; set; }
        public string BackColor { get; set; }
        public bool CalculatedCol { get; set; }
        public string ChildOfCol { get; set; }
        public string Code { get; set; }
        public short ColChars { get; set; }
        public string ColCondition { get; set; }
        public string ColField { get; set; }
        public string ColHead { get; set; }
        public string ColType { get; set; }
        public int ColWidth { get; set; }
        public bool Comma { get; set; }
        public string CondBCLR { get; set; }
        public short Decs { get; set; }
        public bool DisplayGrid { get; set; }
        public bool FitToHeight { get; set; }
        public bool FitToWidth { get; set; }
        public string FldAs { get; set; }
        public bool FontBold { get; set; }
        public bool FontItalics { get; set; }
        public string FontName { get; set; }
        public short FontSize { get; set; }
        public bool FontStrike { get; set; }
        public bool FontUnderLine { get; set; }
        public string ForeColor { get; set; }
        public string FormatString { get; set; }
        public bool GraphCol { get; set; }
        public string GroupHead { get; set; }
        public bool Idle { get; set; }
        public bool IsHidden { get; set; }
        public bool Locked { get; set; }
        public bool pMerge { get; set; }
        public string MergeCond { get; set; }
        public int Sno { get; set; }
        public string SplitColumn { get; set; }
        public string SystemColumn { get; set; }
        public decimal TouchValue { get; set; }
        public bool xCurrency { get; set; }
        public bool YesTotal { get; set; }
        public string Modules { get; set; }
        public short ColPosition { get; set; }
    }
}
