//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFATERPWebApplication.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class TFatBranch
    {
        public int RecordKey { get; set; }
        public string aAuthno { get; set; }
        public string aCity { get; set; }
        public string aCountry { get; set; }
        public string aCstNo { get; set; }
        public string Addrl1 { get; set; }
        public string Addrl2 { get; set; }
        public string Addrl3 { get; set; }
        public string Addrl4 { get; set; }
        public string aFax { get; set; }
        public string aLstno { get; set; }
        public string aPin { get; set; }
        public string AssAreaCode { get; set; }
        public string AssCityCode { get; set; }
        public string AssPincode { get; set; }
        public string aState { get; set; }
        public string aTel1 { get; set; }
        public string aTel2 { get; set; }
        public string aTel3 { get; set; }
        public string aTel4 { get; set; }
        public string AuthIds { get; set; }
        public string Authorise { get; set; }
        public string BranchLocation { get; set; }
        public string Business { get; set; }
        public string Code { get; set; }
        public string Coll { get; set; }
        public string CompCode { get; set; }
        public string Custom { get; set; }
        public string Div { get; set; }
        public string ECCNo { get; set; }
        public string EMail { get; set; }
        public string Flag { get; set; }
        public bool Fri { get; set; }
        public string Grp { get; set; }
        public string HWSerial { get; set; }
        public string HWSerial2 { get; set; }
        public bool LastBranch { get; set; }
        public bool LastUpdated { get; set; }
        public string Licence2 { get; set; }
        public bool LogIn { get; set; }
        public bool Mon { get; set; }
        public string Name { get; set; }
        public string NoteAvail { get; set; }
        public string NoteSno { get; set; }
        public decimal OpCredit { get; set; }
        public decimal OpDebit { get; set; }
        public string PanNo { get; set; }
        public string Range { get; set; }
        public string RegNo { get; set; }
        public bool Sat { get; set; }
        public string ServiceTax { get; set; }
        public bool Sun { get; set; }
        public string Supp { get; set; }
        public string TDSAuthorise { get; set; }
        public string TDSCir { get; set; }
        public string TDSOffice { get; set; }
        public string TDSReg { get; set; }
        public bool Thu { get; set; }
        public string TINNo { get; set; }
        public decimal TouchValue { get; set; }
        public bool Tue { get; set; }
        public string Users { get; set; }
        public string VATReg { get; set; }
        public bool Wed { get; set; }
        public string www { get; set; }
        public string EnteredBy { get; set; }
        public System.DateTime LastUpdateDate { get; set; }
    
        public virtual TfatComp TfatComp { get; set; }
    }
}
