//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFATERPWebApplication.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class TfatCountry
    {
        public TfatCountry()
        {
            this.TfatStates = new HashSet<TfatState>();
        }
    
        public int RecordKey { get; set; }
        public int Code { get; set; }
        public string CountryCode { get; set; }
        public string Name { get; set; }
        public decimal ResourceOffset { get; set; }
        public string CurCode { get; set; }
        public decimal CurDec { get; set; }
        public string CurDecName { get; set; }
        public string CurName { get; set; }
        public decimal CurrRate { get; set; }
        public string DialCode { get; set; }
        public string Lang { get; set; }
        public string LockCode { get; set; }
        public decimal TouchValue { get; set; }
        public string EnteredBy { get; set; }
        public System.DateTime LastUpdateDate { get; set; }
        public string AUTHORISE { get; set; }
        public string AUTHIDS { get; set; }
        public string HWSERIAL { get; set; }
        public string HWSERIAL2 { get; set; }
    
        public virtual ICollection<TfatState> TfatStates { get; set; }
    }
}
