//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFATERPWebApplication.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransportDetail
    {
        public int RecordKey { get; set; }
        public string AccPeriod { get; set; }
        public string AuthIds { get; set; }
        public string Authorise { get; set; }
        public string Branch { get; set; }
        public string ContactPerson { get; set; }
        public string HWSerial { get; set; }
        public string HWSerial2 { get; set; }
        public string NoPkg { get; set; }
        public System.DateTime NoteDate { get; set; }
        public string NoteNo { get; set; }
        public string PeriodCode { get; set; }
        public string Prefix { get; set; }
        public string Remark { get; set; }
        public string Sno { get; set; }
        public string Srl { get; set; }
        public string TransMode { get; set; }
        public string Transporter { get; set; }
        public string Type { get; set; }
        public string VehicleNo { get; set; }
        public decimal TOUCHVALUE { get; set; }
        public string EnteredBy { get; set; }
        public System.DateTime LastUpdateDate { get; set; }
    }
}
