//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFATERPWebApplication.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransporterMa
    {
        public int RecordKey { get; set; }
        public string Addrl1 { get; set; }
        public string Addrl2 { get; set; }
        public string Addrl3 { get; set; }
        public string AuthIds { get; set; }
        public string Authno { get; set; }
        public string Authorise { get; set; }
        public string BranchLocation { get; set; }
        public string City { get; set; }
        public string Code { get; set; }
        public string ContactPerson { get; set; }
        public string Country { get; set; }
        public string CstNo { get; set; }
        public string EMail { get; set; }
        public string Fax { get; set; }
        public string Flag { get; set; }
        public string HWSerial { get; set; }
        public string HWSerial2 { get; set; }
        public string Lstno { get; set; }
        public string Name { get; set; }
        public string PanNo { get; set; }
        public string Pin { get; set; }
        public string State { get; set; }
        public string STaxNo { get; set; }
        public string Tel1 { get; set; }
        public string Tel2 { get; set; }
        public string Tel3 { get; set; }
        public string Tel4 { get; set; }
        public string VATReg { get; set; }
        public string www { get; set; }
        public decimal TOUCHVALUE { get; set; }
        public string EnteredBy { get; set; }
        public System.DateTime LastUpdateDate { get; set; }
    }
}
