//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFATERPWebApplication.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnitMaster1
    {
        public int RecordKey { get; set; }
        public string AuthIds { get; set; }
        public string Authorise { get; set; }
        public decimal Factor1 { get; set; }
        public decimal Factor2 { get; set; }
        public string HWSerial { get; set; }
        public string HWSerial2 { get; set; }
        public decimal Lvl { get; set; }
        public string Name { get; set; }
        public byte NoOfDecimal { get; set; }
        public string Operator1 { get; set; }
        public string Operator2 { get; set; }
        public string ShortName { get; set; }
        public bool Type { get; set; }
        public string Unit1Code { get; set; }
        public string Unit2Code { get; set; }
        public decimal TOUCHVALUE { get; set; }
        public string EnteredBy { get; set; }
        public System.DateTime LastUpdateDate { get; set; }
        public bool Hide { get; set; }
    }
}
